import { describe, expect, test } from "bun:test";

import { normalize3, vec3, vectorToAngles } from "../src/core/math.ts";
import type { Vec3 } from "../src/core/math.ts";
import { bitsToFloat32, float32ToBits } from "../src/core/numeric.ts";

interface AngleFixture {
  readonly name: string;
  readonly input: Vec3;
  readonly angleBits: readonly [number, number, number];
  readonly damageBytes: readonly [number, number];
}

function damageByte(angle: number): number {
  const turns = Math.fround(angle / Math.fround(360));
  return Math.trunc(Math.fround(turns * Math.fround(256))) | 0;
}

function hashWord(hash: number, word: number): number {
  return Math.imul((hash ^ word) >>> 0, 16_777_619) >>> 0;
}

// Generated by compiling the untouched q_math.c vectoangles with the pinned
// Q3 lcc/q3asm toolchain and running it in the original 32-bit QVM interpreter.
// Oracle fixture and output: /tmp/q3-angles-oracle/fixture.c and
// /tmp/quake3-reference-tDKrrk/runtime/angles_oracle/qconsole.log.
describe("QVM vectoangles fixtures", () => {
  const regression = vec3(-4, 0.37, 10);
  const fixtures: readonly AngleFixture[] = [
    { name: "regression", input: regression, angleBits: [3_263_707_780, 1_127_134_997, 0], damageBytes: [-48, 124] },
    { name: "normalized regression", input: normalize3(regression), angleBits: [3_263_707_780, 1_127_134_997, 0], damageBytes: [-48, 124] },
    { name: "diagonal", input: vec3(1, 1, 1), angleBits: [3_255_635_644, 1_110_704_128, 0], damageBytes: [-25, 32] },
    { name: "ordinary octant", input: vec3(-1, 2, -3), angleBits: [3_281_607_040, 1_122_574_669, 0], damageBytes: [-218, 82] },
    { name: "yaw damage boundary", input: vec3(0.00009999999747378752, -0.004073592834174633, 0), angleBits: [2_147_483_648, 1_132_966_912, 0], damageBytes: [0, 193] },
    { name: "pitch damage boundary", input: vec3(0.00009999999747378752, 0.00003333333370392211, 0.0000025876518066070275), angleBits: [3_216_244_735, 1_100_184_262, 0], damageBytes: [0, 13] },
    { name: "+x", input: vec3(1, 0, 0), angleBits: [2_147_483_648, 0, 0], damageBytes: [0, 0] },
    { name: "+x with -0 z", input: vec3(1, 0, -0), angleBits: [0, 0, 0], damageBytes: [0, 0] },
    { name: "-0 x with +z", input: vec3(-0, 0, 1), angleBits: [3_266_576_384, 0, 0], damageBytes: [-64, 0] },
    { name: "zero", input: vec3(0, 0, 0), angleBits: [3_280_404_480, 0, 0], damageBytes: [-192, 0] },
    { name: "+y", input: vec3(0, 1, 0), angleBits: [2_147_483_648, 1_119_092_736, 0], damageBytes: [0, 64] },
    { name: "-y", input: vec3(0, -1, 0), angleBits: [2_147_483_648, 1_132_920_832, 0], damageBytes: [0, 192] },
    { name: "-x", input: vec3(-1, 0, 0), angleBits: [2_147_483_648, 1_127_481_344, 0], damageBytes: [0, 128] },
    { name: "+z", input: vec3(0, 0, 1), angleBits: [3_266_576_384, 0, 0], damageBytes: [-64, 0] },
    { name: "-z", input: vec3(0, 0, -1), angleBits: [3_280_404_480, 0, 0], damageBytes: [-192, 0] },
    { name: "smallest subnormal", input: vec3(bitsToFloat32(1), bitsToFloat32(1), bitsToFloat32(1)), angleBits: [3_266_576_384, 1_110_704_128, 0], damageBytes: [-64, 32] },
    { name: "tiny x with -0 y", input: vec3(bitsToFloat32(0x0da2_4260), -0, 0), angleBits: [2_147_483_648, 2_147_483_648, 0], damageBytes: [0, 0] },
    { name: "maximum x and y", input: vec3(bitsToFloat32(0x7f7f_ffff), bitsToFloat32(0x7f7f_ffff), 1), angleBits: [2_147_483_648, 1_110_704_128, 0], damageBytes: [0, 32] },
    { name: "maximum mixed axes", input: vec3(bitsToFloat32(0x7f7f_ffff), -bitsToFloat32(0x7f7f_ffff), bitsToFloat32(0x7f7f_ffff)), angleBits: [2_147_483_648, 1_134_395_392, 0], damageBytes: [0, 224] },
  ];

  for (const fixture of fixtures) {
    test(`matches ${fixture.name}`, () => {
      const angles = vectorToAngles(fixture.input);
      expect(float32ToBits(angles.x)).toBe(fixture.angleBits[0]);
      expect(float32ToBits(angles.y)).toBe(fixture.angleBits[1]);
      expect(float32ToBits(angles.z)).toBe(fixture.angleBits[2]);
      expect(damageByte(angles.x)).toBe(fixture.damageBytes[0]);
      expect(damageByte(angles.y)).toBe(fixture.damageBytes[1]);
    });
  }

  test("matches eight QVM digests over 1,024 seeded vectors", () => {
    const expected = [
      1_628_032_472,
      723_769_218,
      2_040_724_379,
      468_404_234,
      736_132_166,
      1_035_765_737,
      437_849_002,
      441_172_207,
    ];
    const actual: number[] = [];
    let seed = 0x1234_5678;

    for (let chunk = 0; chunk < expected.length; chunk++) {
      let hash = 2_166_136_261;
      for (let index = 0; index < 128; index++) {
        seed = (Math.imul(69_069, seed) + 1) >>> 0;
        const x = (seed & 65_535) - 32_768;
        seed = (Math.imul(69_069, seed) + 1) >>> 0;
        const y = (seed & 65_535) - 32_768;
        seed = (Math.imul(69_069, seed) + 1) >>> 0;
        const z = (seed & 65_535) - 32_768;
        const input = x === 0 && y === 0 && z === 0 ? vec3(1, 0, 0) : vec3(x, y, z);
        const angles = vectorToAngles(input);
        hash = hashWord(hash, float32ToBits(angles.x));
        hash = hashWord(hash, float32ToBits(angles.y));
        hash = hashWord(hash, float32ToBits(angles.z));
        hash = hashWord(hash, damageByte(angles.x));
        hash = hashWord(hash, damageByte(angles.y));
      }
      actual.push(hash);
    }

    expect(actual).toEqual(expected);
  });
});
