import { afterEach, expect, test } from "bun:test";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { CvarFlag } from "../src/core/cvar.ts";
import { LinuxNativeRandom } from "../src/core/native-random.ts";
import { CommonConsole } from "../src/engine/common-console.ts";
import { StartupCommands } from "../src/engine/startup-commands.ts";
import { SOURCE_PRODUCT_ID } from "./product-id-fixture.ts";
import type { VfsSearchOptions } from "../src/assets/vfs.ts";

const roots: string[] = [], owners: CommonConsole[] = [];
afterEach(() => {
  for (const owner of owners.splice(0)) owner.close();
  for (const root of roots.splice(0)) rmSync(root, { recursive: true });
});

function fixture() {
  const root = mkdtempSync(join(tmpdir(), "q3-synthetic-cdkey-")); roots.push(root);
  const dataPath = join(root, "data"), homePath = join(root, "home"), cdPath = join(root, "cd");
  for (const path of [dataPath, homePath, cdPath]) {
    for (const game of ["baseq3", "missionpack", "demota"]) mkdirSync(join(path, game), { recursive: true });
  }
  writeFileSync(join(dataPath, "baseq3", "default.cfg"), "set synthetic_fixture 1\n");
  writeFileSync(join(dataPath, "baseq3", "productid.txt"), SOURCE_PRODUCT_ID);
  writeFileSync(join(dataPath, "demota", "default.cfg"), "set synthetic_demo 1\n");
  return { dataPath, homePath, cdPath, product: "baseq3" } satisfies VfsSearchOptions;
}

async function open(paths: ReturnType<typeof fixture>, game = "", build: "client" | "dedicated" = "client",
  usesUniqueKey: () => number | Promise<number> = () => 0, print: (text: string) => undefined = () => undefined,
  startup = "") {
  return CommonConsole.open({ roots: paths, startup: new StartupCommands(`${startup} +set fs_game "${game}"`),
    random: new LinuxNativeRandom(1), platformPrint: print, assertCommandEntry: () => undefined,
    assertOwnerEntry: () => undefined, resolveCommand: () => undefined,
    build: build === "dedicated" ? { kind: "dedicated" } : { kind: "client", client: {
      initializeKeyCommands: () => {}, writeBindings: () => {}, consolePrint: () => {}, usesUniqueKey,
    } },
  }, owner => { owners.push(owner); });
}

function authorization(common: CommonConsole): Uint8Array {
  const bytes = new Uint8Array(33); common.cdKey.readAuthorization(bytes); return bytes;
}

function initialize(common: CommonConsole): void {
  common.registerRuntimeCvars("synthetic-cdkey", async () => undefined);
  common.markInitialized();
}

const trailer = "\n// generated by quake, do not modify\r\n// Do not give this file to ANYONE.\r\n"
  + "// id Software and Activision will NOT ask you to send this file to them.\r\n";

test("ordinary startup reads home base key then the mod data key and product restart reloads both slots", async () => {
  const paths = fixture();
  writeFileSync(join(paths.homePath, "baseq3", "q3key"), "a".repeat(16) + "ignored suffix");
  writeFileSync(join(paths.dataPath, "baseq3", "q3key"), "B".repeat(16));
  writeFileSync(join(paths.dataPath, "missionpack", "q3key"), "C".repeat(16));
  const printed: string[] = [], common = await open(paths, "missionpack", "client", () => 1, text => { printed.push(text); });
  expect(authorization(common)).toEqual(new Uint8Array([...new Uint8Array(16).fill(97), ...new Uint8Array(16).fill(67), 0]));
  expect(common.files.roots.product).toBe("missionpack");
  initialize(common);
  writeFileSync(join(paths.homePath, "baseq3", "q3key"), "D".repeat(16));
  writeFileSync(join(paths.dataPath, "missionpack", "q3key"), "G".repeat(16));
  await common.files.restart({ checksumFeed: 12, random: () => 0 }, () => {});
  expect(authorization(common)).toEqual(new Uint8Array([...new Uint8Array(16).fill(68), ...new Uint8Array(16).fill(71), 0]));
  common.cvars.set("fs_game", "", true);
  await common.files.restart({ checksumFeed: 13, random: () => 0 }, () => {});
  expect(common.files.roots.product).toBe("baseq3");
  // Com_ReadCDKey overwrites byte sixteen, but preserves the rest of the old second slot.
  expect(authorization(common)).toEqual(new Uint8Array([...new Uint8Array(16).fill(68), 0, ...new Uint8Array(15).fill(71), 0]));
  expect(printed.join("")).not.toContain("a".repeat(16));
});

test("only initialized ordinary read handles apply the source case-sensitive q3key guard", async () => {
  const paths = fixture();
  for (const name of ["q3key", "Q3KEY", "quake3cdkey.md", "saved-q3key.cfg"]) {
    writeFileSync(join(paths.homePath, "baseq3", name), "A".repeat(16));
  }
  const common = await open(paths);
  expect(common.files.current.readFileLength("q3key")).toBe(16);
  initialize(common);
  expect(common.files.current.readFileLength("q3key")).toBe(-1);
  expect(common.files.openByMode("saved-q3key.cfg", "read")).toBeUndefined();
  expect(common.files.current.readFileLength("Q3KEY")).toBe(16);
  expect(common.files.current.readFileLength("quake3cdkey.md")).toBe(16);
  expect(common.files.current.has("q3key")).toBe(true);
  expect(common.files.server.exists("baseq3/q3key")).toBe(true);
  const file = common.files.server.openRead("baseq3/q3key");
  if (file === null) throw new Error("Ordinary source server read was denied");
  const bytes = new Uint8Array(16);
  expect(common.files.readFile(file.file.slot, bytes)).toBe(16);
  common.files.closeFile(file.file.slot);
  expect(bytes).toEqual(new Uint8Array(16).fill(65));
});

test("client archive save awaits the live UI choice after config output and persists its selected key", async () => {
  const paths = fixture();
  writeFileSync(join(paths.homePath, "baseq3", "q3key"), "A".repeat(16));
  writeFileSync(join(paths.homePath, "missionpack", "q3key"), "B".repeat(16));
  let choose: () => Promise<number> = async () => 0, calls = 0;
  const common = await open(paths, "missionpack", "client", () => { calls++; return choose(); });
  common.cdKey.writeUiForCompiledModule(() => 1, () => new Uint8Array(16).fill(67));
  await common.writeConfiguration();
  expect(calls).toBe(0);
  initialize(common);
  common.cdKey.writeUiForCompiledModule(() => 1, () => new Uint8Array(16).fill(67));
  common.cvars.set("fs_game", "", true);
  let release: (value: number) => void = () => { throw new Error("UI has not been invoked"); };
  choose = () => {
    expect(existsSync(join(paths.homePath, "missionpack", "q3config.cfg"))).toBe(true);
    return new Promise<number>(resolve => { release = resolve; });
  };
  const pending = common.writeConfiguration();
  expect(calls).toBe(1);
  expect(readFileSync(join(paths.homePath, "missionpack", "q3key"), "latin1")).toBe("B".repeat(16));
  common.cvars.set("fs_game", "missionpack", true);
  release(1); await pending;
  expect(readFileSync(join(paths.homePath, "missionpack", "q3key"), "latin1")).toBe("C".repeat(16) + trailer);
  expect(readFileSync(join(paths.homePath, "baseq3", "q3key"), "latin1")).toBe("A".repeat(16));
  await common.writeConfiguration(); expect(calls).toBe(1);
  choose = async () => 2;
  common.cvars.markModifiedFlags(CvarFlag.Archive); await common.writeConfiguration();
  expect(readFileSync(join(paths.homePath, "baseq3", "q3key"), "latin1")).toBe("A".repeat(16) + trailer);
});

test("explicit writeconfig never writes keys and a failed automatic config open still reaches the client key write", async () => {
  const paths = fixture();
  writeFileSync(join(paths.homePath, "baseq3", "q3key"), "A".repeat(16));
  let calls = 0;
  const common = await open(paths, "", "client", () => { calls++; return 1; });
  initialize(common);
  common.cdKey.writeUiForCompiledModule(() => 0, () => new Uint8Array(16).fill(68));
  common.commands.executeNow("writeconfig explicit");
  expect(calls).toBe(0);
  expect(readFileSync(join(paths.homePath, "baseq3", "q3key"), "latin1")).toBe("A".repeat(16));
  mkdirSync(join(paths.homePath, "baseq3", "q3config.cfg"));
  await common.writeConfiguration();
  expect(calls).toBe(1);
  expect(readFileSync(join(paths.homePath, "baseq3", "q3key"), "latin1")).toBe("D".repeat(16) + trailer);
});

test("dedicated startup accepts unvalidated keys but archive saves never persist changed key memory", async () => {
  const paths = fixture();
  writeFileSync(join(paths.homePath, "baseq3", "q3key"), "X".repeat(16));
  writeFileSync(join(paths.homePath, "missionpack", "q3key"), "B".repeat(16));
  const common = await open(paths, "missionpack", "dedicated");
  expect(authorization(common)).toEqual(new Uint8Array([...new Uint8Array(16).fill(88), ...new Uint8Array(16).fill(66), 0]));
  initialize(common);
  common.cdKey.writeUiForCompiledModule(() => 1, () => new Uint8Array(16).fill(67));
  await common.writeConfiguration();
  expect(existsSync(join(paths.homePath, "missionpack", "q3config.cfg"))).toBe(true);
  expect(readFileSync(join(paths.homePath, "missionpack", "q3key"), "latin1")).toBe("B".repeat(16));
  writeFileSync(join(paths.homePath, "baseq3", "q3key"), "x\0ignored");
  common.cdKey.readFile("baseq3", common.files);
  expect(authorization(common)).toEqual(new Uint8Array([120, ...new Uint8Array(16), ...new Uint8Array(15).fill(67), 0]));
  writeFileSync(join(paths.homePath, "missionpack", "q3key"), "xy\0ignored");
  common.cdKey.appendFile("missionpack", common.files);
  expect(authorization(common)).toEqual(new Uint8Array([120, ...new Uint8Array(15), 120, 121, 0, ...new Uint8Array(13).fill(67), 0]));
  writeFileSync(join(paths.homePath, "baseq3", "q3key"), "");
  common.cdKey.readFile("baseq3", common.files);
  expect(authorization(common).subarray(0, 17)).toEqual(new Uint8Array(17));
});

test("restricted demo remount repeats base and mod key loading at the same startup boundary", async () => {
  const paths = fixture();
  writeFileSync(join(paths.homePath, "baseq3", "q3key"), "A".repeat(16));
  writeFileSync(join(paths.homePath, "missionpack", "q3key"), "B".repeat(16));
  const common = await open(paths, "missionpack", "client", () => 1, text => {
    if (text === "\nRunning in restricted demo mode.\n\n") {
      writeFileSync(join(paths.homePath, "baseq3", "q3key"), "D".repeat(16));
      writeFileSync(join(paths.homePath, "missionpack", "q3key"), "short");
    }
  }, "+set fs_restrict 1");
  expect(common.files.writable.rootPath).toBe(join(paths.homePath, "demota"));
  expect(authorization(common)).toEqual(new Uint8Array([...new Uint8Array(16).fill(68), ...new Uint8Array(16).fill(32), 0]));
});
