// Common key storage and client validation from id Software common.c, cl_main.c and cl_ui.c.
// Copyright (C) 1999-2005 Id Software, Inc. GPL-2.0-or-later.
import { CvarFlag } from "../core/cvar.ts";
import type { CvarRegistry } from "../core/cvar.ts";
import { sourceCommandText } from "../core/text.ts";
import type { CommonFileState } from "../assets/filesystem-state.ts";

type CdKeyReadFiles = Pick<CommonFileState, "readFile" | "closeFile"> & {
  readonly server: Pick<CommonFileState["server"], "openRead">;
};
type CdKeyWriteFiles = { readonly server: Pick<CommonFileState["server"], "openWrite"> };

function cdKeyPath(directory: string): string {
  const path = `${sourceCommandText(directory)}/q3key`;
  // Source sprintf has undefined behavior beyond the selected Unix MAX_OSPATH.
  if (path.length >= 4096) throw new RangeError("CD key filename exceeds Unix MAX_OSPATH");
  return path;
}

function readKeyFile(directory: string, files: CdKeyReadFiles, build: "client" | "dedicated"): Uint8Array | null {
  const opened = files.server.openRead(cdKeyPath(directory));
  if (opened === null) return null;
  const buffer = new Uint8Array(33);
  // Server loose handles are not streamed; common's readFile reaches FS_Read's loop.
  files.readFile(opened.file.slot, buffer.subarray(0, 16));
  files.closeFile(opened.file.slot);
  // null_client.c accepts all input in a dedicated build.
  return build === "dedicated" || validateCdKey(String.fromCharCode(...buffer.subarray(0, 16)), null) ? buffer : null;
}

export function validateCdKey(key: string, checksum: string | null): boolean {
  key = sourceCommandText(key);
  if (checksum !== null) checksum = sourceCommandText(checksum);
  if (key.length !== 16 || (checksum !== null && checksum.length !== 2)) return false;
  let sum = 0;
  for (let index = 0; index < key.length; index++) {
    let character = key.charCodeAt(index);
    if (character >= 97 && character <= 122) character -= 32;
    if (!"237ABCDGHJLPRSTW".includes(String.fromCharCode(character))) return false;
    sum = (sum + character) & 255;
  }
  return checksum === null || checksum.toLowerCase() === sum.toString(16).padStart(2, "0");
}

export class CommonCdKeyState {
  private readonly bytes = new Uint8Array(34);

  constructor(private readonly cvars: CvarRegistry, private readonly build: "client" | "dedicated") {
    if (build === "client") this.bytes.fill(32, 0, 32);
    else for (let index = 0; index < 9; index++) this.bytes[index] = 49 + index;
  }

  /** Com_ReadCDKey. The base terminator also clears the first unique-key byte. */
  readFile(directory: string, files: CdKeyReadFiles): void {
    const buffer = readKeyFile(directory, files, this.build);
    if (buffer === null) {
      this.bytes.fill(32, 0, 16); this.bytes[16] = 0;
    } else {
      // Q_strncpyz uses strncpy, including its padding after an embedded NUL.
      buffer.fill(0, buffer.indexOf(0));
      this.bytes.set(buffer.subarray(0, 17));
    }
  }

  /** Com_AppendCDKey uses strcat at offset sixteen, retaining an existing prefix. */
  appendFile(directory: string, files: CdKeyReadFiles): void {
    const buffer = readKeyFile(directory, files, this.build);
    if (buffer === null) {
      this.bytes.fill(32, 16, 32); this.bytes[32] = 0;
      return;
    }
    const end = this.bytes.indexOf(0, 16);
    const length = buffer.indexOf(0) + 1;
    if (end < 0 || end + length > this.bytes.length) throw new RangeError("Undefined CD key strcat allocation overflow");
    this.bytes.set(buffer.subarray(0, length), end);
  }

  /** Com_WriteCDKey. Client-only caller selection remains owned by common. */
  writeFile(directory: string, offset: 0 | 16, files: CdKeyWriteFiles, print: (text: string) => undefined): void {
    const path = cdKeyPath(directory), key = this.bytes.slice(offset, offset + 16);
    if (!validateCdKey(String.fromCharCode(...key), null)) return;
    const file = files.server.openWrite(path);
    if (file === null) { print(`Couldn't write ${sourceCommandText(directory)}.\n`); return; }
    file.writeBytes(key);
    const encoder = new TextEncoder();
    file.writeBytes(encoder.encode("\n// generated by quake, do not modify\r\n"));
    file.writeBytes(encoder.encode("// Do not give this file to ANYONE.\r\n"));
    file.writeBytes(encoder.encode("// id Software and Activision will NOT ask you to send this file to them.\r\n"));
    file.close();
  }

  readAuthorization(destination: Uint8Array): void {
    if (destination.length < 33) throw new RangeError("CD key authorization destination requires 33 bytes");
    destination.set(this.bytes.subarray(0, 32));
    destination[32] = 0;
  }

  readUiForCompiledModule(usesUniqueKey: () => number, destination: () => Uint8Array): void {
    const offset = this.compiledModuleOffset(usesUniqueKey), bytes = destination();
    if (bytes.length < 17) throw new RangeError("CD key UI destination requires 17 bytes");
    this.copyUi(offset, bytes);
  }

  writeUiForCompiledModule(usesUniqueKey: () => number, source: () => Uint8Array): void {
    const offset = this.compiledModuleOffset(usesUniqueKey), bytes = source();
    if (bytes.length < 16) throw new RangeError("CD key UI source requires 16 bytes");
    this.storeUi(offset, bytes);
  }

  async readUiForModule(usesUniqueKey: () => number | Promise<number>, destination: () => Uint8Array): Promise<void> {
    const offset = await this.moduleOffset(usesUniqueKey), bytes = destination();
    if (bytes.length < 17) throw new RangeError("CD key UI destination requires 17 bytes");
    this.copyUi(offset, bytes);
  }

  async writeUiForModule(usesUniqueKey: () => number | Promise<number>, source: () => Uint8Array): Promise<void> {
    const offset = await this.moduleOffset(usesUniqueKey), bytes = source();
    if (bytes.length < 16) throw new RangeError("CD key UI source requires 16 bytes");
    this.storeUi(offset, bytes);
  }

  private copyUi(offset: 0 | 16, destination: Uint8Array): void {
    destination.set(this.bytes.subarray(offset, offset + 16));
    destination[16] = 0;
  }

  private storeUi(offset: 0 | 16, source: Uint8Array): void {
    this.bytes.set(source.subarray(0, 16), offset);
    if (offset === 16) this.bytes[32] = 0;
    this.cvars.markModifiedFlags(CvarFlag.Archive);
  }

  private async moduleOffset(usesUniqueKey: () => number | Promise<number>): Promise<0 | 16> {
    const handle = this.cvars.bindVm("fs_game", "", CvarFlag.Init | CvarFlag.SystemInfo);
    return this.uiOffset(handle, await usesUniqueKey());
  }

  private compiledModuleOffset(usesUniqueKey: () => number): 0 | 16 {
    const handle = this.cvars.bindVm("fs_game", "", CvarFlag.Init | CvarFlag.SystemInfo);
    return this.uiOffset(handle, usesUniqueKey());
  }

  private uiOffset(handle: number, usesUniqueKey: number): 0 | 16 {
    // UI_usesUniqueCDKey compares the returned VM word with qtrue, not with zero.
    if (usesUniqueKey !== 1) return 0;
    const game = this.cvars.readVm(handle);
    if (game === undefined) throw new Error("UI key selection lost its registered fs_game allocation");
    return game.value.length === 0 ? 0 : 16;
  }
}
