import { inventorySource } from "./inventory.ts";
import type { SourceInventoryFile } from "./inventory.ts";

interface Mapping {
  readonly sources: readonly string[];
  readonly targets: readonly string[];
  readonly evidence: readonly string[];
}

const mappings: readonly Mapping[] = [
  { sources: ["botlib/be_aas_file.c"], targets: ["src/botlib/aas.ts", "src/botlib/aas-storage.ts", "src/botlib/aas-runtime.ts"], evidence: ["tests/aas.test.ts", "tests/aas-runtime.test.ts"] },
  { sources: ["renderer/tr_sky.c"], targets: ["src/render/sun.ts", "src/render/world.ts", "src/render/settings.ts"], evidence: ["tests/sun.test.ts"] },
  { sources: ["renderer/tr_surface.c"], targets: ["src/render/tess-state.ts", "src/render/commands.ts", "src/render/cpu/rasterizer.ts", "src/render/gl/renderer.ts", "src/platform/gl.ts"], evidence: ["tests/display-list.test.ts"] },
  { sources: ["client/cl_cin.c"], targets: ["src/cinematic/roq-codebook.ts"], evidence: ["tests/roq-codebook.test.ts"] },
  { sources: ["ui/menudef.h"], targets: ["src/ui/menu.ts", "src/ui/runtime.ts", "src/render/font.ts", "src/cgame/mission-owner-draw.ts", "src/cgame/mission-hud.ts", "src/ui/team-arena/owner-draw.ts", "src/ui/team-arena/owner-keys.ts", "src/ui/team-arena/visibility.ts", "src/ui/team-arena/feeders.ts", "src/game/ai-voice.ts"], evidence: ["tests/menu.test.ts", "tests/cgame-mission-owner-draw.test.ts", "tests/team-arena-owner-draw.test.ts", "docs/source-examination.tsv"] },
  { sources: ["q3_ui/ui_loadconfig.c"], targets: ["src/ui/base/load-config.ts", "src/ui/base/ui.ts"], evidence: ["tests/base-ui-load-config.test.ts", "docs/source-examination.tsv"] },
  { sources: ["q3_ui/ui_options.c"], targets: ["src/ui/base/system-config.ts", "src/ui/base/ui.ts"], evidence: ["tests/base-ui-system-config.test.ts", "docs/source-examination.tsv"] },
  { sources: ["cgame/cg_syscalls.asm", "ui/ui_syscalls.asm"], targets: ["src/vm/interpreter.ts", "src/engine/client.ts"], evidence: ["tests/qvm-interpreter.test.ts", "tests/qvm-cgame.test.ts", "tests/qvm-ui.test.ts", "docs/source-examination.tsv"] },
  { sources: ["game/g_syscalls.asm"], targets: ["src/vm/interpreter.ts", "src/engine/server-engine.ts"], evidence: ["tests/qvm-interpreter.test.ts", "tests/qvm-game.test.ts", "tests/server-engine.test.ts", "docs/source-examination.tsv"] },
  { sources: ["botlib/be_aas_bsp.h"], targets: ["src/botlib/bsp-entities.ts","src/botlib/spatial.ts","src/botlib/entity.ts"], evidence: ["tests/aas-spatial.test.ts","tests/aas-entity.test.ts"] },
  { sources: ["botlib/be_aas_cluster.h"], targets: ["src/botlib/aas-cluster.ts"], evidence: ["tests/aas-cluster.test.ts"] },
  { sources: ["botlib/be_aas_debug.h"], targets: ["src/botlib/aas-debug.ts","src/botlib/aas-reachability-special.ts","src/botlib/library.ts"], evidence: ["tests/bot-debug.test.ts"] },
  { sources: ["botlib/be_aas_entity.h"], targets: ["src/botlib/entity.ts","src/botlib/aas-runtime.ts","src/botlib/spatial.ts"], evidence: ["tests/aas-entity.test.ts","tests/aas-runtime.test.ts"] },
  { sources: ["botlib/be_aas_file.h"], targets: ["src/botlib/aas.ts","src/botlib/aas-file.ts","src/botlib/aas-world.ts","src/botlib/aas-runtime.ts"], evidence: ["tests/aas.test.ts","tests/aas-file.test.ts","tests/aas-runtime.test.ts"] },
  { sources: ["botlib/be_aas_funcs.h"], targets: ["src/botlib/aas-runtime.ts","src/botlib/spatial.ts","src/botlib/routing.ts"], evidence: ["tests/aas-runtime.test.ts","tests/bot-library.test.ts"] },
  { sources: ["botlib/be_aas_main.h"], targets: ["src/botlib/aas-runtime.ts","src/botlib/aas-world.ts","src/botlib/movement-routing.ts"], evidence: ["tests/aas-runtime.test.ts","tests/bot-movement-routing.test.ts"] },
  { sources: ["botlib/be_aas_move.h"], targets: ["src/botlib/aas-movement.ts","src/botlib/spatial.ts"], evidence: ["tests/aas-movement.test.ts","tests/aas-spatial.test.ts"] },
  { sources: ["botlib/be_aas_optimize.h"], targets: ["src/botlib/aas-optimize.ts"], evidence: ["tests/aas-optimize.test.ts"] },
  { sources: ["botlib/be_aas_reach.h"], targets: ["src/botlib/aas-reachability.ts","src/botlib/aas-reachability-geometry.ts","src/botlib/aas-reachability-special.ts","src/botlib/spatial.ts","src/botlib/aas-runtime.ts"], evidence: ["tests/aas-reachability.test.ts","tests/aas-reachability-special.test.ts","tests/aas-spatial.test.ts"] },
  { sources: ["botlib/be_aas_route.h"], targets: ["src/botlib/routing.ts","src/botlib/routing-storage.ts","src/botlib/aas-route-cache.ts","src/botlib/aas-runtime.ts"], evidence: ["tests/aas.test.ts","tests/aas-route-cache.test.ts","tests/aas-runtime.test.ts"] },
  { sources: ["botlib/be_aas_sample.h"], targets: ["src/botlib/spatial.ts","src/botlib/aas-links.ts","src/botlib/aas-runtime.ts","src/botlib/aas-world.ts"], evidence: ["tests/aas-spatial.test.ts","tests/aas-entity.test.ts","tests/aas-runtime.test.ts"] },
  { sources: ["botlib/be_ai_weight.h"], targets: ["src/botlib/weights.ts"], evidence: ["tests/bot-weights.test.ts"] },
  { sources: ["botlib/be_interface.h"], targets: ["src/botlib/library.ts","src/botlib/aas-runtime.ts"], evidence: ["tests/bot-library.test.ts","tests/bot-debug.test.ts","tests/aas-runtime.test.ts"] },
  { sources: ["botlib/l_crc.h"], targets: ["src/botlib/aas-route-cache.ts"], evidence: ["tests/aas-route-cache.test.ts"] },
  { sources: ["botlib/l_precomp.h"], targets: ["src/script/preprocessor.ts","src/script/precomp-memory.ts","src/script/source-memory.ts","src/botlib/script-sources.ts"], evidence: ["tests/script-preprocessor.test.ts","tests/script-source-reader.test.ts","tests/script-source-handles.test.ts","tests/script-globals.test.ts"] },
  { sources: ["botlib/l_script.h"], targets: ["src/script/lexer.ts","src/script/token-memory.ts","src/script/source-memory.ts","src/script/memory.ts","src/botlib/script-sources.ts"], evidence: ["tests/script-lexer.test.ts","tests/script-source-reader.test.ts","tests/bot-script-sources.test.ts"] },
  { sources: ["botlib/l_utils.h"], targets: ["src/core/math.ts","src/botlib/spatial.ts","src/botlib/script-sources.ts"], evidence: ["tests/aas-spatial.test.ts","tests/bot-script-sources.test.ts"] },
  { sources: ["cgame/cg_public.h"], targets: ["src/protocol/server-message.ts","src/cgame/snapshot-history.ts","src/engine/qvm-cgame.ts","src/engine/client.ts","src/vm/client-state-syscalls.ts"], evidence: ["tests/qvm-cgame.test.ts","tests/qvm-client-state.test.ts"] },
  { sources: ["client/snd_local.h"], targets: ["src/audio/mixer.ts","src/audio/adpcm.ts","src/audio/wavelet.ts","src/cgame/sound-bank.ts","src/engine/sound.ts","src/engine/sound-frame.ts","src/engine/sound-output.ts"], evidence: ["tests/audio.test.ts","tests/adpcm.test.ts","tests/wavelet.test.ts","tests/sound-frame.test.ts","tests/sound-output.test.ts"] },
  { sources: ["client/snd_public.h"], targets: ["src/engine/sound.ts","src/engine/sound-output.ts","src/engine/sound-frame.ts","src/audio/music.ts","src/audio/mixer.ts"], evidence: ["tests/audio.test.ts","tests/music.test.ts","tests/sound-output.test.ts"] },
  { sources: ["game/ai_chat.h"], targets: ["src/game/ai-chat.ts"], evidence: ["docs/STATUS.md"] },
  { sources: ["game/ai_cmd.h"], targets: ["src/game/ai-command.ts"], evidence: ["docs/STATUS.md"] },
  { sources: ["game/ai_team.h"], targets: ["src/game/ai-team.ts"], evidence: ["docs/STATUS.md"] },
  { sources: ["game/ai_vcmd.h"], targets: ["src/game/ai-voice.ts"], evidence: ["docs/STATUS.md"] },
  { sources: ["game/be_aas.h"], targets: ["src/botlib/spatial.ts","src/botlib/entity.ts","src/botlib/aas-runtime.ts","src/botlib/aas-movement.ts","src/botlib/routing.ts","src/vm/aas-record.ts"], evidence: ["tests/aas-runtime.test.ts","tests/aas-movement.test.ts","tests/qvm-aas.test.ts"] },
  { sources: ["game/be_ai_char.h"], targets: ["src/botlib/character.ts"], evidence: ["tests/bot-character.test.ts"] },
  { sources: ["game/be_ai_goal.h"], targets: ["src/botlib/goals.ts","src/vm/bot-goal-record.ts","src/vm/bot-goal-syscalls.ts"], evidence: ["tests/bot-goals.test.ts","tests/qvm-bot-goals.test.ts"] },
  { sources: ["game/be_ai_move.h"], targets: ["src/botlib/movement-state.ts","src/botlib/movement.ts","src/botlib/movement-routing.ts","src/botlib/spatial.ts","src/vm/bot-movement-syscalls.ts"], evidence: ["tests/bot-movement-routing.test.ts","tests/qvm-bot-movement.test.ts"] },
  { sources: ["game/bg_lib.h"], targets: ["src/game/numeric.ts","src/game/format.ts","src/core/numeric.ts","src/core/qvm-math.ts","src/vm/memory-syscalls.ts","src/vm/math-syscalls.ts"], evidence: ["tests/game-numeric.test.ts","tests/qvm-math.test.ts","tests/qvm-memory.test.ts"] },
  { sources: ["game/bg_local.h"], targets: ["src/shared/movement.ts","src/shared/slide-move.ts"], evidence: ["tests/movement.test.ts"] },
  { sources: ["game/botlib.h"], targets: ["src/botlib/library.ts","src/botlib/actions.ts","src/botlib/entity.ts","src/botlib/aas-runtime.ts","src/vm/bot-library-syscalls.ts","src/engine/server-engine.ts"], evidence: ["tests/bot-library.test.ts","tests/qvm-bot-library.test.ts"] },
  { sources: ["game/g_team.h"], targets: ["src/game/team.ts","src/game/missile.ts","src/shared/movement.ts"], evidence: ["tests/game-team.test.ts","tests/movement.test.ts"] },
  { sources: ["game/surfaceflags.h"], targets: ["src/render/material-flags.ts","src/shared/movement.ts","src/game/weapon.ts","src/game/missile.ts","src/game/item-lifecycle.ts","src/game/ai-navigation.ts"], evidence: ["tests/movement.test.ts","tests/game-weapon.test.ts"] },
  { sources: ["q3_ui/keycodes.h"], targets: ["src/core/key-codes.ts"], evidence: ["tests/sdl-game-input.test.ts"] },
  { sources: ["q3_ui/ui_local.h"], targets: ["src/ui/base/state.ts","src/ui/base/framework.ts","src/ui/base/cvars.ts","src/ui/base/ui.ts","src/ui/base/draw.ts","src/ui/base/field.ts"], evidence: ["docs/STATUS.md"] },
  { sources: ["qcommon/cm_local.h"], targets: ["src/collision/world.ts","src/collision/topology.ts","src/collision/model.ts","src/collision/clip-models.ts","src/collision/patch.ts"], evidence: ["tests/collision.test.ts","tests/collision-model.test.ts"] },
  { sources: ["qcommon/cm_patch.h","qcommon/cm_polylib.h"], targets: ["src/collision/patch.ts","src/collision/world.ts"], evidence: ["tests/collision.test.ts","tests/collision-patch-native.test.ts"] },
  { sources: ["qcommon/cm_public.h"], targets: ["src/collision/world.ts","src/collision/topology.ts","src/collision/clip-models.ts","src/collision/map-loader.ts","src/collision/map-resource.ts","src/vm/collision-syscalls.ts"], evidence: ["tests/collision.test.ts","tests/qvm-collision.test.ts"] },
  { sources: ["qcommon/qcommon.h"], targets: ["src/protocol/message.ts","src/protocol/netchan.ts","src/core/commands.ts","src/core/cvar.ts","src/engine/common-console.ts","src/engine/common-frame.ts","src/assets/vfs.ts","src/vm/registry.ts"], evidence: ["tests/common-frame.test.ts","tests/common-console.test.ts","tests/vm-registry.test.ts"] },
  { sources: ["qcommon/unzip.h"], targets: ["src/assets/pk3.ts","src/assets/vfs.ts","src/assets/inflate.ts"], evidence: ["docs/COMPATIBILITY.md"] },
  { sources: ["renderer/qgl_linked.h","renderer/qgl.h"], targets: ["src/platform/gl.ts","src/render/gl/renderer.ts"], evidence: ["tests/gl-renderer.test.ts"] },
  { sources: ["renderer/tr_local.h"], targets: ["src/render/types.ts","src/render/material.ts","src/render/tess-state.ts","src/render/world.ts","src/render/commands.ts"], evidence: ["tests/tess-state.test.ts","tests/world.test.ts"] },
  { sources: ["renderer/tr_public.h"], targets: ["src/render/world.ts","src/render/commands.ts","src/engine/client.ts","src/vm/render-resource-syscalls.ts","src/vm/render-scene-syscalls.ts"], evidence: ["tests/qvm-renderer-handles.test.ts","tests/client-level.test.ts"] },
  { sources: ["cgame/cg_syscalls.c"], targets: ["src/engine/client.ts","src/core/numeric.ts","src/vm/common-syscalls.ts","src/vm/client-state-syscalls.ts","src/vm/collision-syscalls.ts","src/vm/render-resource-syscalls.ts","src/vm/render-scene-syscalls.ts","src/vm/render-world-syscalls.ts","src/vm/sound-syscalls.ts","src/vm/script-syscalls.ts","src/vm/cinematic-syscalls.ts","src/vm/key-syscalls.ts","src/vm/font-syscalls.ts","src/vm/mark-syscalls.ts"], evidence: ["tests/qvm-cgame.test.ts","tests/qvm-client-state.test.ts"] },
  { sources: ["game/g_syscalls.c"], targets: ["src/engine/server-engine.ts","src/core/numeric.ts","src/vm/common-syscalls.ts","src/vm/server-game-syscalls.ts","src/vm/server-bot-syscalls.ts","src/vm/bot-library-syscalls.ts","src/vm/aas-syscalls.ts","src/vm/bot-action-syscalls.ts","src/vm/bot-character-syscalls.ts","src/vm/bot-chat-syscalls.ts","src/vm/bot-goal-syscalls.ts","src/vm/bot-movement-syscalls.ts","src/vm/bot-weapon-syscalls.ts","src/vm/bot-genetic-syscalls.ts","src/vm/script-syscalls.ts"], evidence: ["tests/qvm-game.test.ts","tests/server-engine.test.ts"] },
  { sources: ["ui/ui_syscalls.c"], targets: ["src/engine/client.ts","src/vm/common-syscalls.ts","src/vm/filesystem-syscalls.ts","src/vm/render-resource-syscalls.ts","src/vm/render-scene-syscalls.ts","src/vm/sound-syscalls.ts","src/vm/client-state-syscalls.ts","src/vm/browser-syscalls.ts","src/vm/key-syscalls.ts","src/vm/ui-key-syscalls.ts","src/vm/script-syscalls.ts","src/vm/real-time-syscalls.ts","src/vm/cinematic-syscalls.ts","src/vm/font-syscalls.ts"], evidence: ["tests/qvm-ui.test.ts","tests/qvm-browser.test.ts"] },
  { sources: ["qcommon/vm_ppc_new.c","qcommon/vm_ppc.c","qcommon/vm_x86.c"], targets: ["src/vm/interpreter.ts","src/vm/operations.ts","src/assets/qvm.ts"], evidence: ["tests/qvm-interpreter.test.ts","tests/qvm-operations.test.ts","docs/GROUNDING.md"] },
  { sources: ["game/g_rankings.c","game/g_rankings.h","server/sv_rankings.c","q3_ui/ui_loadconfig.c","q3_ui/ui_login.c","q3_ui/ui_options.c","q3_ui/ui_rankings.c","q3_ui/ui_rankstatus.c","q3_ui/ui_signup.c","q3_ui/ui_specifyleague.c","q3_ui/ui_spreset.c","ui/ui_util.c"], targets: [], evidence: ["docs/GROUNDING.md"] },
  { sources: ["qcommon/vm.c", "qcommon/vm_interpreted.c", "client/cl_ui.c", "client/cl_cgame.c", "server/sv_game.c"], targets: ["src/vm/registry.ts", "src/vm/symbols.ts", "src/vm/interpreter.ts", "src/vm/syscall-log.ts", "src/engine/client-modules.ts", "src/engine/common-console.ts", "src/engine/common-hunk.ts", "src/engine/client.ts", "src/engine/server-engine.ts", "src/ui/base/ui.ts", "src/ui/team-arena/ui.ts", "src/game/runtime.ts", "src/cgame/client-level.ts"], evidence: ["tests/vm-registry.test.ts", "tests/qvm-symbols.test.ts", "tests/vm-syscall-log.test.ts", "tests/base-ui-vm-trace.test.ts", "tests/team-arena-vm-trace.test.ts", "tests/game-vm-trace.test.ts", "tests/cgame-vm-trace.test.ts", "tests/common-console.test.ts", "tests/client-modules.test.ts", "tests/server-engine.test.ts", "docs/STATUS.md"] },
  { sources: ["unix/unix_main.c", "unix/linux_glimp.c", "unix/linux_joystick.c"], targets: ["src/platform/system-init.ts", "src/platform/source-input.ts", "src/platform/sdl-game-input.ts", "src/engine/common-frame.ts", "src/engine/client-host.ts", "src/engine/client.ts"], evidence: ["tests/common-frame.test.ts", "tests/sdl-game-input.test.ts", "docs/STATUS.md"] },
  { sources: ["unix/linux_qgl.c", "unix/linux_glimp.c", "renderer/tr_backend.c", "renderer/tr_shade.c"], targets: ["src/render/gl/logging.ts", "src/render/gl/renderer.ts", "src/platform/gl.ts", "src/engine/screen.ts", "src/render/commands.ts", "src/assets/writable-files.ts"], evidence: ["tests/gl-renderer.test.ts", "tests/writable-files.test.ts", "docs/STATUS.md"] },
  { sources: ["client/cl_ui.c", "q3_ui/ui_cdkey.c", "q3_ui/ui_main.c", "ui/ui_main.c"], targets: ["src/engine/cd-key.ts", "src/ui/base/cd-key.ts", "src/ui/base/main-menu.ts", "src/ui/base/ui.ts", "src/ui/team-arena/menu-scripts.ts", "src/ui/team-arena/ui.ts"], evidence: ["tests/engine-cd-key.test.ts", "tests/base-ui-cd-key.test.ts", "tests/base-ui-main-menu.test.ts", "tests/team-arena-menu-scripts.test.ts"] },
  { sources: ["client/snd_dma.c"], targets: ["src/engine/sound-output.ts", "src/engine/sound-frame.ts", "src/platform/audio.ts"], evidence: ["tests/sound-output.test.ts", "tests/sound-frame.test.ts", "tests/sdl-audio.test.ts"] },
  { sources: ["server/sv_ccmds.c", "server/sv_net_chan.c"], targets: ["src/engine/server-engine.ts", "src/server/connectionless.ts", "src/server/net-channel.ts", "src/server/network-control.ts", "src/server/bot-adapter.ts"], evidence: ["tests/server-engine.test.ts", "tests/server-connectionless.test.ts", "tests/server-net-channel.test.ts"] },
  { sources: ["client/cl_parse.c", "client/client.h"], targets: ["src/protocol/parse-entities.ts", "src/engine/client-active.ts"], evidence: ["tests/client-game-state.test.ts", "tests/cgame-snapshots.test.ts"] },
  { sources: ["qcommon/common.c", "qcommon/cvar.c", "qcommon/cmd.c"], targets: ["src/core/zone.ts", "src/core/zone-strings.ts", "src/core/cvar.ts", "src/core/commands.ts", "src/engine/common-console.ts"], evidence: ["tests/zone.test.ts", "tests/core/cvar.test.ts", "tests/core/commands.test.ts", "tests/common-console.test.ts"] },
  { sources: ["botlib/l_libvar.c"], targets: ["src/botlib/libvars.ts", "src/botlib/library.ts"], evidence: ["tests/libvars.test.ts", "tests/bot-libvars-memory.test.ts"] },
  { sources: ["botlib/be_aas_file.c", "botlib/be_aas_cluster.c", "botlib/be_aas_optimize.c"], targets: ["src/botlib/aas-storage.ts", "src/botlib/aas-world.ts", "src/botlib/aas-optimize.ts"], evidence: ["tests/aas.test.ts", "tests/aas-cluster.test.ts", "tests/aas-optimize.test.ts"] },
  { sources: ["client/snd_adpcm.c"], targets: ["src/audio/adpcm.ts"], evidence: ["tests/adpcm.test.ts", "docs/COMPATIBILITY.md"] },
  { sources: ["client/snd_wavelet.c"], targets: ["src/audio/wavelet.ts"], evidence: ["tests/wavelet.test.ts", "docs/COMPATIBILITY.md"] },
  { sources: ["jpeg-6/jdphuff.c", "jpeg-6/jdinput.c", "jpeg-6/jdcoefct.c"], targets: ["src/assets/jpeg.ts"], evidence: ["tests/jpeg.test.ts", "docs/COMPATIBILITY.md"] },
  { sources: ["game/g_mem.c", "game/g_spawn.c", "game/g_bot.c", "game/ai_main.c"], targets: ["src/game/memory.ts", "src/game/spawn.ts", "src/game/bots.ts", "src/game/ai-state.ts", "src/game/ai-main.ts"], evidence: ["tests/game-memory.test.ts", "tests/game-bots.test.ts", "tests/game-spawn.test.ts"] },
  { sources: ["qcommon/common.c", "qcommon/files.c", "qcommon/vm.c", "renderer/tr_image.c", "renderer/tr_shader.c", "client/snd_mem.c", "server/sv_init.c"], targets: ["src/engine/common-hunk.ts", "src/assets/read-file-memory.ts", "src/render/shader-text.ts", "src/render/hunk-accounting.ts", "src/engine/client.ts", "src/engine/server-engine.ts", "src/server/snapshot-entities.ts"], evidence: ["tests/hunk.test.ts", "tests/read-file-memory.test.ts", "tests/hunk-resources.test.ts", "tests/server-state.test.ts", "docs/COMPATIBILITY.md"] },
  { sources: ["qcommon/cm_load.c", "server/sv_init.c", "client/cl_cgame.c"], targets: ["src/collision/map-loader.ts", "src/collision/map-resource.ts", "src/cgame/client-level.ts", "src/engine/client.ts", "src/engine/server-engine.ts"], evidence: ["tests/collision-map-loader.test.ts", "tests/client-level.test.ts", "tests/server-engine.test.ts"] },
  { sources: ["qcommon/vm.c", "client/cl_ui.c", "client/cl_cgame.c", "server/sv_game.c"], targets: ["src/engine/client-modules.ts", "src/engine/qvm-ui.ts", "src/engine/qvm-cgame.ts", "src/engine/qvm-game.ts", "src/vm/game-data.ts", "src/vm/server-game-syscalls.ts", "src/engine/server-engine.ts"], evidence: ["tests/qvm-ui.test.ts", "tests/qvm-cgame.test.ts", "tests/qvm-game.test.ts", "tests/qvm-game-data.test.ts", "tests/server-engine.test.ts"] },
  { sources: ["client/cl_cgame.c", "client/cl_ui.c", "server/sv_game.c", "botlib/be_interface.c"], targets: ["src/vm/real-time-syscalls.ts", "src/vm/bot-library-syscalls.ts", "src/vm/aas-syscalls.ts", "src/vm/bot-action-syscalls.ts", "src/vm/bot-character-syscalls.ts", "src/vm/bot-chat-syscalls.ts", "src/vm/bot-goal-syscalls.ts", "src/vm/bot-movement-syscalls.ts", "src/vm/bot-weapon-syscalls.ts", "src/vm/bot-genetic-syscalls.ts"], evidence: ["tests/qvm-real-time.test.ts", "tests/qvm-bot-library.test.ts", "tests/qvm-aas.test.ts", "tests/qvm-bot-actions.test.ts", "tests/qvm-bot-character.test.ts", "tests/qvm-bot-chat.test.ts", "tests/qvm-bot-goals.test.ts", "tests/qvm-bot-movement.test.ts", "tests/qvm-bot-weapons.test.ts", "tests/qvm-bot-genetic.test.ts"] },
  { sources: ["cgame/cg_newdraw.c", "cgame/cg_particles.c", "cgame/cg_scoreboard.c"], targets: ["src/cgame/mission-hud.ts", "src/cgame/particles.ts", "src/cgame/scoreboard.ts"], evidence: ["tests/cgame-mission-hud.test.ts", "tests/cgame-particles.test.ts", "tests/cgame-scoreboard.test.ts"] },
  { sources: ["qcommon/qfiles.h", "qcommon/vm_local.h", "qcommon/vm.c", "qcommon/vm_interpreted.c"], targets: ["src/assets/qvm.ts", "src/vm/interpreter.ts", "src/vm/operations.ts"], evidence: ["tests/qvm.test.ts", "tests/qvm-interpreter.test.ts", "tests/qvm-operations.test.ts", "docs/COMPATIBILITY.md"] },
  { sources: ["client/cl_cgame.c", "client/cl_ui.c", "server/sv_game.c", "qcommon/common.c"], targets: ["src/vm/common-syscalls.ts", "src/vm/math-syscalls.ts", "src/vm/memory-syscalls.ts", "src/vm/vector-syscalls.ts", "src/vm/cvar-syscalls.ts", "src/vm/console-syscalls.ts"], evidence: ["tests/qvm-interpreter.test.ts", "tests/qvm-memory.test.ts", "tests/qvm-vector.test.ts", "tests/qvm-cvar.test.ts", "tests/qvm-console.test.ts"] },
  { sources: ["qcommon/vm.c", "game/q_shared.c"], targets: ["src/vm/memory.ts", "src/core/info-string.ts"], evidence: ["tests/qvm-memory.test.ts", "tests/info-string.test.ts", "tests/core/cvar.test.ts"] },
  { sources: ["game/q_shared.h"], targets: ["src/vm/user-command.ts", "src/vm/entity-record.ts", "src/vm/player-record.ts"], evidence: ["tests/qvm-user-command.test.ts", "tests/qvm-entity-record.test.ts", "tests/qvm-player-record.test.ts", "tests/qvm-interpreter.test.ts"] },
  { sources: ["client/cl_cgame.c", "client/cl_ui.c", "server/sv_game.c", "qcommon/files.c"], targets: ["src/vm/filesystem-syscalls.ts"], evidence: ["tests/qvm-filesystem.test.ts"] },
  { sources: ["client/cl_cgame.c", "client/cl_ui.c", "renderer/tr_model.c", "renderer/tr_shader.c", "renderer/tr_cmds.c"], targets: ["src/vm/render-record.ts", "src/vm/render-resource-syscalls.ts"], evidence: ["tests/qvm-render-record.test.ts", "tests/qvm-renderer-handles.test.ts", "tests/world-material-registration.test.ts"] },
  { sources: ["client/cl_cgame.c", "client/cl_ui.c", "client/snd_dma.c"], targets: ["src/vm/sound-syscalls.ts"], evidence: ["tests/qvm-sound.test.ts"] },
  { sources: ["client/cl_parse.c", "client/cl_cgame.c", "client/cl_ui.c", "game/q_shared.h"], targets: ["src/engine/game-state.ts", "src/vm/client-record.ts"], evidence: ["tests/client-game-state.test.ts", "tests/qvm-client-record.test.ts"] },
  { sources: ["client/cl_cgame.c", "client/cl_ui.c", "client/cl_keys.c"], targets: ["src/vm/client-state-syscalls.ts", "src/vm/key-syscalls.ts"], evidence: ["tests/qvm-client-state.test.ts", "tests/qvm-key.test.ts"] },
  { sources: ["client/cl_cgame.c", "client/cl_ui.c", "client/cl_cin.c"], targets: ["src/vm/cinematic-syscalls.ts"], evidence: ["tests/qvm-cinematic.test.ts", "docs/COMPATIBILITY.md"] },
  { sources: ["client/cl_cgame.c", "qcommon/cm_load.c", "qcommon/cm_trace.c", "qcommon/cm_test.c"], targets: ["src/collision/clip-models.ts", "src/vm/collision-syscalls.ts", "src/vm/trace-record.ts"], evidence: ["tests/qvm-collision.test.ts", "tests/collision-model.test.ts", "docs/COMPATIBILITY.md"] },
  { sources: ["client/cl_cgame.c", "client/cl_ui.c", "renderer/tr_font.c"], targets: ["src/render/font-registry.ts", "src/vm/font-syscalls.ts"], evidence: ["tests/qvm-font.test.ts", "tests/font.test.ts"] },
  { sources: ["client/cl_ui.c"], targets: ["src/vm/browser-syscalls.ts", "src/engine/server-browser.ts"], evidence: ["tests/qvm-browser.test.ts", "tests/server-browser.test.ts"] },
  { sources: ["client/cl_cgame.c", "client/cl_ui.c", "renderer/tr_scene.c", "renderer/tr_world.c", "renderer/tr_bsp.c"], targets: ["src/vm/render-scene-syscalls.ts", "src/vm/render-world-syscalls.ts", "src/render/scene-submission.ts", "src/render/world.ts"], evidence: ["tests/qvm-render-scene.test.ts", "tests/scene-numeric-admission.test.ts", "tests/scene-numeric-render.test.ts"] },
  { sources: ["client/cl_cgame.c", "client/cl_ui.c", "server/sv_game.c", "botlib/l_precomp.c", "botlib/l_script.c", "game/q_shared.h"], targets: ["src/vm/script-syscalls.ts", "src/vm/script-record.ts", "src/botlib/script-sources.ts", "src/script/preprocessor.ts", "src/script/lexer.ts"], evidence: ["tests/script-source-handles.test.ts", "tests/script-source-reader.test.ts", "tests/qvm-script-record.test.ts"] },
  { sources: ["game/q_math.c"], targets: ["src/core/math.ts", "src/core/numeric.ts"], evidence: ["tests/math.test.ts", "tests/numeric.test.ts", "tests/angles-qvm.test.ts"] },
  { sources: ["game/q_shared.c"], targets: ["src/core/text.ts", "src/core/common-parse.ts"], evidence: ["tests/core/text.test.ts", "tests/common-parse.test.ts"] },
  { sources: ["game/q_shared.h", "game/bg_public.h"], targets: ["src/shared/definitions.ts", "src/shared/player-state.ts", "src/shared/entity-state.ts", "src/shared/trajectory.ts"], evidence: ["tests/shared.test.ts", "tests/movement.test.ts", "tests/state-delta.test.ts"] },
  { sources: ["qcommon/cvar.c"], targets: ["src/core/cvar.ts"], evidence: ["tests/core/cvar.test.ts", "tests/cvar-vm-words.test.ts"] },
  { sources: ["qcommon/cmd.c"], targets: ["src/core/commands.ts"], evidence: ["tests/core/commands.test.ts"] },
  { sources: ["qcommon/common.c"], targets: ["src/core/info-string.ts"], evidence: ["tests/client-console-commands.test.ts", "tests/server-engine.test.ts"] },
  { sources: ["qcommon/common.c", "qcommon/files.c", "unix/unix_main.c"], targets: ["src/engine/common-journal.ts", "src/engine/common-console.ts", "src/engine/common-frame.ts", "src/engine/common-events.ts", "src/engine/event-memory.ts", "src/platform/unix-io.ts", "src/assets/vfs.ts", "src/assets/filesystem-state.ts"], evidence: ["tests/common-console.test.ts", "tests/common-frame.test.ts", "tests/common-events.test.ts", "tests/dedicated-input.test.ts"] },
  { sources: ["qcommon/files.c", "qcommon/unzip.c"], targets: ["src/assets/pk3.ts", "src/assets/vfs.ts"], evidence: ["tests/pk3.test.ts", "tests/vfs.test.ts"] },
  { sources: ["qcommon/files.c"], targets: ["src/assets/file-handles.ts", "src/assets/filesystem-state.ts", "src/assets/writable-files.ts", "src/assets/server-files.ts"], evidence: ["tests/fs-handles.test.ts", "tests/fs-lifetime.test.ts", "tests/fs-pure.test.ts", "tests/vfs-file-list.test.ts", "tests/writable-files.test.ts", "tests/fs-server.test.ts", "tests/aas-file.test.ts"] },
  { sources: ["qcommon/unzip.c"], targets: ["src/assets/pk3.ts", "src/assets/inflate.ts"], evidence: ["tests/pk3-cursor.test.ts", "tests/inflate.test.ts"] },
  { sources: ["q3_ui/ui_gameinfo.c"], targets: ["src/ui/base/game-info.ts"], evidence: ["tests/base-ui-game-info.test.ts"] },
  { sources: ["ui/ui_main.c", "ui/ui_shared.c"], targets: ["src/ui/team-arena/memory.ts", "src/ui/team-arena/game-info.ts", "src/ui/team-arena/team-info.ts"], evidence: ["tests/team-arena-info.test.ts"] },
  { sources: ["ui/ui_gameinfo.c", "game/q_shared.c"], targets: ["src/ui/team-arena/catalog.ts", "src/core/common-parse.ts"], evidence: ["tests/team-arena-catalog.test.ts", "tests/common-parse.test.ts"] },
  { sources: ["ui/ui_main.c", "game/q_shared.c", "game/bg_lib.c"], targets: ["src/ui/team-arena/models.ts"], evidence: ["tests/team-arena-models.test.ts"] },
  { sources: ["ui/ui_atoms.c", "ui/ui_local.h"], targets: ["src/ui/team-arena/scores.ts", "src/ui/team-arena/postgame.ts"], evidence: ["tests/team-arena-scores.test.ts"] },
  { sources: ["ui/ui_main.c", "ui/ui_public.h"], targets: ["src/ui/team-arena/menu-controller.ts", "src/ui/public.ts"], evidence: ["tests/team-arena-scores.test.ts", "tests/base-ui-controller.test.ts"] },
  { sources: ["ui/ui_main.c", "ui/ui_shared.c"], targets: ["src/ui/team-arena/menu-loader.ts", "src/ui/team-arena/visibility.ts", "src/ui/team-arena/settings.ts"], evidence: ["tests/team-arena-menu-loader.test.ts", "tests/team-arena-scores.test.ts", "tests/ui-runtime.test.ts"] },
  { sources: ["ui/ui_main.c", "ui/ui_atoms.c", "ui/ui_shared.c", "ui/ui_local.h"], targets: ["src/ui/team-arena/feeders.ts", "src/ui/team-arena/interaction-state.ts", "src/ui/team-arena/refresh.ts", "src/ui/team-arena/console-commands.ts"], evidence: ["tests/team-arena-feeders.test.ts", "tests/team-arena-menu-loader.test.ts", "tests/ui-runtime.test.ts"] },
  { sources: ["ui/ui_players.c", "ui/ui_local.h"], targets: ["src/ui/team-arena/players.ts"], evidence: ["tests/team-arena-players.test.ts", "tests/base-ui-player-animation.test.ts"] },
  { sources: ["ui/ui_main.c", "ui/ui_local.h"], targets: ["src/ui/team-arena/owner-keys.ts"], evidence: ["tests/team-arena-owner-keys.test.ts", "tests/team-arena-feeders.test.ts"] },
  { sources: ["ui/ui_main.c", "ui/ui_local.h"], targets: ["src/ui/team-arena/owner-draw.ts", "src/ui/team-arena/menu-scripts.ts", "src/ui/team-arena/ui.ts"], evidence: ["tests/team-arena-owner-draw.test.ts", "tests/team-arena-menu-scripts.test.ts", "tests/team-arena-menu-loader.test.ts"] },
  { sources: ["ui/ui_main.c", "client/cl_ui.c", "qcommon/common.c", "game/bg_lib.c"], targets: ["src/ui/team-arena/server-browser.ts", "src/ui/team-arena/server-status.ts", "src/platform/system-clock.ts"], evidence: ["tests/team-arena-server-browser.test.ts", "tests/team-arena-server-status.test.ts", "tests/system-clock.test.ts"] },
  { sources: ["ui/ui_main.c", "client/cl_cin.c"], targets: ["src/ui/team-arena/connect-screen.ts", "src/ui/team-arena/cinematics.ts"], evidence: ["tests/team-arena-connect-screen.test.ts", "tests/team-arena-cinematics.test.ts"] },
  { sources: ["ui/ui_main.c"], targets: ["src/ui/team-arena/selection.ts", "src/ui/team-arena/resources.ts", "src/ui/team-arena/lists.ts", "src/ui/team-arena/player-list.ts"], evidence: ["tests/team-arena-info.test.ts", "tests/team-arena-resources.test.ts", "tests/team-arena-lists.test.ts", "tests/team-arena-player-list.test.ts"] },
  { sources: ["q3_ui/ui_players.c"], targets: ["src/ui/base/player-animation.ts", "src/ui/base/players.ts"], evidence: ["tests/base-ui-player-animation.test.ts", "tests/base-ui-players.test.ts"] },
  { sources: ["q3_ui/ui_sparena.c"], targets: ["src/ui/base/sp-arena.ts"], evidence: ["tests/base-ui-sp-skill.test.ts"] },
  { sources: ["q3_ui/ui_spskill.c"], targets: ["src/ui/base/sp-skill.ts"], evidence: ["tests/base-ui-sp-skill.test.ts"] },
  { sources: ["q3_ui/ui_addbots.c", "game/bg_lib.c"], targets: ["src/ui/base/add-bots.ts"], evidence: ["tests/base-ui-add-bots.test.ts"] },
  { sources: ["q3_ui/ui_removebots.c"], targets: ["src/ui/base/remove-bots.ts"], evidence: ["tests/base-ui-remove-bots.test.ts"] },
  { sources: ["q3_ui/ui_controls2.c"], targets: ["src/ui/base/controls.ts"], evidence: ["tests/base-ui-controls.test.ts"] },
  { sources: ["q3_ui/ui_demo2.c"], targets: ["src/ui/base/demos.ts"], evidence: ["tests/base-ui-demos.test.ts"] },
  { sources: ["q3_ui/ui_playermodel.c"], targets: ["src/ui/base/player-model.ts"], evidence: ["tests/base-ui-player-model.test.ts"] },
  { sources: ["q3_ui/ui_playersettings.c"], targets: ["src/ui/base/player-settings.ts"], evidence: ["tests/base-ui-player-settings.test.ts"] },
  { sources: ["q3_ui/ui_startserver.c", "game/bg_lib.c"], targets: ["src/ui/base/start-server.ts"], evidence: ["tests/base-ui-start-server.test.ts"] },
  { sources: ["q3_ui/ui_main.c"], targets: ["src/ui/base/cvars.ts"], evidence: ["tests/base-ui-cvars.test.ts"] },
  { sources: ["q3_ui/ui_atoms.c", "q3_ui/ui_main.c"], targets: ["src/ui/base/ui.ts"], evidence: ["tests/base-ui-controller.test.ts", "tests/engine-screen.test.ts"] },
  { sources: ["q3_ui/ui_splevel.c"], targets: ["src/ui/base/sp-level.ts"], evidence: ["tests/base-ui-sp-level.test.ts"] },
  { sources: ["q3_ui/ui_sppostgame.c"], targets: ["src/ui/base/medals.ts", "src/ui/base/sp-postgame.ts"], evidence: ["tests/base-ui-sp-postgame.test.ts"] },
  { sources: ["q3_ui/ui_mods.c"], targets: ["src/ui/base/mods.ts"], evidence: ["tests/base-ui-mods.test.ts"] },
  { sources: ["q3_ui/ui_menu.c"], targets: ["src/ui/base/main-menu.ts"], evidence: ["tests/base-ui-main-menu.test.ts"] },
  { sources: ["q3_ui/ui_setup.c", "q3_ui/ui_ingame.c"], targets: ["src/ui/base/setup.ts", "src/ui/base/ingame.ts"], evidence: ["tests/base-ui-setup-ingame.test.ts"] },
  { sources: ["q3_ui/ui_video.c"], targets: ["src/ui/base/graphics-options.ts"], evidence: ["tests/base-ui-graphics-options.test.ts"] },
  { sources: ["q3_ui/ui_display.c"], targets: ["src/ui/base/display-options.ts"], evidence: ["tests/base-ui-display-options.test.ts"] },
  { sources: ["q3_ui/ui_servers2.c"], targets: ["src/ui/base/arena-servers.ts"], evidence: ["tests/base-ui-arena-servers.test.ts"] },
  { sources: ["qcommon/qfiles.h", "qcommon/cm_load.c"], targets: ["src/assets/bsp.ts", "src/assets/md3.ts"], evidence: ["tests/bsp.test.ts", "tests/md3.test.ts", ".artifacts/missionpack-assets.json"] },
  { sources: ["qcommon/cm_trace.c", "qcommon/cm_test.c", "qcommon/cm_patch.c", "qcommon/cm_polylib.c"], targets: ["src/collision/world.ts", "src/collision/patch.ts"], evidence: ["tests/collision.test.ts"] },
  { sources: ["qcommon/cm_load.c", "qcommon/cm_patch.c", "qcommon/cm_test.c", "qcommon/cm_trace.c"], targets: ["src/collision/world.ts", "src/collision/patch.ts", "src/engine/common-console.ts", "src/engine/server-engine.ts", "src/engine/client.ts", "src/cgame/client-level.ts"], evidence: ["tests/collision.test.ts", "tests/collision-topology.test.ts", "docs/STATUS.md"] },
  { sources: ["game/bg_misc.c"], targets: ["src/shared/items.ts", "src/shared/trajectory.ts"], evidence: ["tests/shared.test.ts"] },
  { sources: ["game/bg_pmove.c", "game/bg_slidemove.c"], targets: ["src/shared/movement.ts", "src/shared/slide-move.ts"], evidence: ["tests/movement.test.ts"] },
  { sources: ["game/g_client.c"], targets: ["src/engine/local-player.ts"], evidence: ["tests/local-player.test.ts"] },
  { sources: ["qcommon/huffman.c", "qcommon/msg.c", "qcommon/net_chan.c", "client/cl_net_chan.c", "server/sv_net_chan.c"], targets: ["src/protocol/huffman.ts", "src/protocol/message.ts", "src/protocol/netchan.ts"], evidence: ["tests/huffman.test.ts", "tests/message.test.ts", "tests/netchan.test.ts"] },
  { sources: ["qcommon/msg.c"], targets: ["src/protocol/state-delta.ts"], evidence: ["tests/state-delta.test.ts"] },
  { sources: ["renderer/tr_image.c"], targets: ["src/assets/tga.ts", "src/assets/jpeg.ts", "src/assets/pcx.ts", "src/assets/bmp.ts", "src/render/image-loader.ts", "src/render/world.ts"], evidence: ["tests/tga.test.ts", "tests/jpeg.test.ts", "tests/pcx.test.ts", "tests/bmp.test.ts", "tests/world-image-upload.test.ts"] },
  { sources: ["jpeg-6/jddctmgr.c", "jpeg-6/jidctflt.c", "jpeg-6/jdmaster.c"], targets: ["src/assets/jpeg.ts"], evidence: ["tests/jpeg.test.ts", "docs/COMPATIBILITY.md"] },
  { sources: ["renderer/tr_image.c", "jpeg-6/jcparam.c", "jpeg-6/jccolor.c", "jpeg-6/jcsample.c", "jpeg-6/jccoefct.c", "jpeg-6/jcdctmgr.c", "jpeg-6/jfdctflt.c", "jpeg-6/jchuff.c", "jpeg-6/jcmarker.c"], targets: ["src/assets/jpeg-encoder.ts"], evidence: ["tests/jpeg-encoder.test.ts", "docs/COMPATIBILITY.md"] },
  { sources: ["qcommon/qfiles.h", "renderer/tr_model.c"], targets: ["src/assets/md4.ts"], evidence: ["tests/md4-model.test.ts", "docs/STATUS.md"] },
  { sources: ["renderer/tr_model.c", "renderer/tr_animation.c"], targets: ["src/render/md4-resource.ts"], evidence: ["tests/md4-resource.test.ts", "docs/STATUS.md"] },
  { sources: ["renderer/tr_model.c", "renderer/tr_animation.c", "renderer/tr_scene.c", "renderer/tr_shade.c", "renderer/tr_shadows.c"], targets: ["src/render/scene-models.ts", "src/render/model-tags.ts", "src/render/model-bounds.ts", "src/render/tess-state.ts", "src/render/picture-material.ts", "src/render/stencil-shadows.ts", "src/render/world.ts"], evidence: ["tests/md4-registration.test.ts", "tests/md4-scene.test.ts", "tests/tess-state.test.ts", "tests/stencil-shadows.test.ts", "docs/STATUS.md"] },
  { sources: ["renderer/tr_scene.c", "renderer/tr_cmds.c", "renderer/tr_light.c", "renderer/tr_init.c"], targets: ["src/render/backend-memory.ts", "src/render/hunk-accounting.ts", "src/render/scene-entities.ts", "src/render/scene-entity-memory.ts", "src/render/scene-submission.ts", "src/render/scene-submission-memory.ts"], evidence: ["tests/hunk.test.ts", "tests/scene-entities.test.ts", "tests/scene-submission.test.ts", "docs/STATUS.md"] },
  { sources: ["renderer/tr_main.c", "renderer/tr_scene.c", "renderer/tr_cmds.c", "renderer/tr_backend.c", "renderer/tr_shader.c"], targets: ["src/render/draw-sort.ts", "src/render/draw-surfaces.ts", "src/render/command-memory.ts", "src/render/commands.ts", "src/render/material-registry.ts", "src/render/world.ts"], evidence: ["tests/render-commands.test.ts", "tests/world-prepared.test.ts", "tests/material-registry.test.ts", "tests/scene-submission.test.ts", "docs/COMPATIBILITY.md"] },
  { sources: ["renderer/tr_init.c", "renderer/tr_cmds.c", "renderer/tr_backend.c", "client/cl_scrn.c", "cgame/cg_view.c", "cgame/cg_draw.c"], targets: ["src/render/settings.ts", "src/render/configuration.ts", "src/render/commands.ts", "src/render/cpu/rasterizer.ts", "src/render/gl/renderer.ts", "src/platform/gl.ts", "src/platform/sdl.ts", "src/engine/client.ts", "src/engine/screen.ts", "src/cgame/client-level.ts"], evidence: ["tests/render-settings.test.ts", "tests/render-commands.test.ts", "tests/client-level.test.ts", "docs/STATUS.md"] },
  { sources: ["renderer/tr_init.c", "renderer/tr_cmds.c", "renderer/tr_backend.c", "client/cl_main.c", "qcommon/files.c"], targets: ["src/engine/screenshots.ts", "src/render/screenshot.ts", "src/engine/client.ts", "src/render/commands.ts"], evidence: ["tests/screenshot.test.ts", "docs/STATUS.md"] },
  { sources: ["renderer/tr_init.c", "renderer/tr_mesh.c", "renderer/tr_main.c", "renderer/tr_bsp.c"], targets: ["src/render/settings.ts", "src/render/model-geometry.ts", "src/render/scene-models.ts", "src/render/world.ts"], evidence: ["tests/render-settings.test.ts", "tests/model-geometry.test.ts", "tests/model-scene.test.ts", "tests/render-view.test.ts"] },
  { sources: ["qcommon/files.c", "unix/unix_shared.c"], targets: ["src/engine/common-console.ts", "src/assets/vfs.ts", "src/assets/file-handles.ts", "src/assets/writable-files.ts", "src/assets/server-files.ts"], evidence: ["tests/common-console.test.ts", "tests/vfs-file-list.test.ts"] },
  { sources: ["renderer/tr_image.c", "renderer/tr_init.c", "unix/linux_glimp.c"], targets: ["src/render/image-upload.ts", "src/render/image-resource.ts", "src/render/builtin-images.ts", "src/render/settings.ts", "src/render/configuration.ts", "src/render/cpu/rasterizer.ts", "src/render/cpu/lines.ts", "src/render/gl/renderer.ts", "src/platform/sdl.ts", "src/engine/client.ts"], evidence: ["tests/image-upload.test.ts", "tests/image-resource.test.ts", "tests/cpu-mipmap.test.ts", "tests/gl-mipmap.test.ts", "tests/world-image-upload.test.ts", "tests/sdl-pixel-selection.test.ts", "tests/engine-client-video.test.ts", "docs/STATUS.md"] },
  { sources: ["renderer/tr_flares.c", "renderer/tr_surface.c", "renderer/tr_shader.c"], targets: ["src/render/flares.ts", "src/render/world.ts", "src/render/settings.ts", "src/render/commands.ts", "src/render/cpu/rasterizer.ts", "src/render/gl/renderer.ts"], evidence: ["tests/flares.test.ts", "tests/cpu-flare-depth.test.ts", "tests/gl-flare-depth.test.ts", "tests/flare-dispatch.test.ts", "tests/render-settings.test.ts", "docs/STATUS.md"] },
  { sources: ["renderer/tr_model.c", "renderer/tr_mesh.c"], targets: ["src/assets/md3.ts", "src/render/md3-resource.ts"], evidence: ["tests/md3.test.ts", "tests/md4-registration.test.ts", "tests/model-geometry.test.ts"] },
  { sources: ["renderer/tr_world.c", "renderer/tr_bsp.c", "renderer/tr_main.c", "renderer/tr_scene.c", "renderer/tr_curve.c"], targets: ["src/render/world.ts", "src/render/visibility.ts", "src/render/bsp-resource.ts", "src/render/patch.ts", "src/render/patch-lod.ts"], evidence: ["tests/world.test.ts", "tests/patch-lod.test.ts", ".artifacts/render/q3dm1.json"] },
  { sources: ["renderer/tr_shadows.c"], targets: ["src/render/deform.ts", "src/render/scene-models.ts", "src/render/world.ts"], evidence: ["tests/scene-effects.test.ts", "tests/model-scene.test.ts"] },
  { sources: ["renderer/tr_shadows.c", "renderer/tr_cmds.c", "renderer/tr_backend.c", "renderer/tr_init.c"], targets: ["src/render/stencil-shadows.ts", "src/render/tess-state.ts", "src/render/commands.ts", "src/render/cpu/rasterizer.ts", "src/render/gl/renderer.ts", "src/render/settings.ts", "src/engine/client.ts", "src/engine/screen.ts"], evidence: ["tests/stencil-shadows.test.ts", "tests/engine-client-stencil.test.ts", "tests/world.test.ts", "tests/render-settings.test.ts", "docs/STATUS.md"] },
  { sources: ["renderer/tr_main.c", "renderer/tr_backend.c", "renderer/tr_sky.c"], targets: ["src/render/portal.ts", "src/render/world.ts", "src/render/commands.ts", "src/render/cpu/rasterizer.ts", "src/render/gl/renderer.ts"], evidence: ["tests/portal.test.ts", "tests/world.test.ts", "tests/render-commands.test.ts"] },
  { sources: ["renderer/tr_shader.c", "renderer/tr_shade_calc.c"], targets: ["src/render/material.ts"], evidence: ["tests/material.test.ts"] },
  { sources: ["renderer/tr_init.c", "renderer/tr_image.c", "renderer/tr_model.c", "renderer/tr_shader.c"], targets: ["src/render/image-resource.ts", "src/render/material-registry.ts", "src/render/scene-models.ts", "src/render/configuration.ts", "src/render/settings.ts", "src/render/world.ts", "src/engine/client.ts"], evidence: ["tests/image-resource.test.ts", "tests/material-registry.test.ts", "tests/md4-registration.test.ts", "tests/renderer-configuration.test.ts", "tests/render-settings.test.ts", "tests/engine-client-video.test.ts"] },
  { sources: ["renderer/tr_backend.c", "renderer/tr_shade.c"], targets: ["src/render/gl/renderer.ts", "src/render/cpu/rasterizer.ts"], evidence: ["tests/gl-renderer.test.ts", "tests/rasterizer.test.ts", "tools/verify-render.ts"] },
  { sources: ["renderer/tr_shade.c", "renderer/tr_init.c"], targets: ["src/render/primitives.ts", "src/render/picture-material.ts", "src/render/commands.ts", "src/render/settings.ts", "src/render/configuration.ts", "src/render/cpu/rasterizer.ts", "src/render/gl/renderer.ts", "src/platform/gl.ts"], evidence: ["tests/render-primitives.test.ts", "tests/source-stage-data.test.ts", "tests/cpu-primitives.test.ts", "tests/gl-primitives.test.ts", "tests/render-commands.test.ts", "tests/render-settings.test.ts", "tests/renderer-configuration.test.ts"] },
  { sources: ["renderer/tr_shade.c", "renderer/tr_backend.c", "renderer/tr_init.c", "renderer/tr_sky.c"], targets: ["src/render/debug-draw.ts", "src/render/types.ts", "src/render/picture-material.ts", "src/render/world.ts", "src/render/commands.ts", "src/render/settings.ts", "src/render/cpu/rasterizer.ts", "src/render/gl/renderer.ts", "src/platform/gl.ts"], evidence: ["tests/render-debug-producer.test.ts", "tests/cpu-debug-draw.test.ts", "tests/gl-debug-draw.test.ts", "tests/render-commands.test.ts", "tests/render-settings.test.ts", "tests/world.test.ts", "tests/stencil-shadows.test.ts"] },
  { sources: ["server/sv_ccmds.c"], targets: ["src/engine/server-engine.ts"], evidence: ["tests/server-engine.test.ts", "docs/STATUS.md"] },
  { sources: ["client/snd_mem.c"], targets: ["src/assets/wav.ts"], evidence: ["tests/wav.test.ts"] },
  { sources: ["client/snd_mem.c", "client/snd_mix.c", "client/snd_dma.c"], targets: ["src/audio/mixer.ts"], evidence: ["tests/audio.test.ts"] },
  { sources: ["client/snd_dma.c"], targets: ["src/engine/sound-output.ts"], evidence: ["tests/sound-output.test.ts"] },
  { sources: ["client/cl_main.c", "client/client.h"], targets: ["src/engine/client-admission.ts", "src/engine/client-authorization.ts", "src/engine/client-state.ts"], evidence: ["tests/engine-client-admission.test.ts"] },
  { sources: ["client/cl_main.c", "client/cl_parse.c", "qcommon/files.c"], targets: ["src/assets/client-download.ts", "src/engine/client-download.ts", "src/engine/client.ts"], evidence: ["tests/client-downloads.test.ts", "tests/fs-pure.test.ts"] },
  { sources: ["client/cl_main.c"], targets: ["src/engine/client-demo-playback.ts", "src/protocol/demo.ts", "src/engine/client.ts"], evidence: ["tests/client-demo-playback.test.ts", "tests/demo.test.ts"] },
  { sources: ["client/cl_main.c"], targets: ["src/engine/client-motd.ts", "src/engine/client.ts"], evidence: ["tests/engine-client-motd.test.ts", "docs/STATUS.md"] },
  { sources: ["renderer/tr_shade.c", "renderer/tr_world.c", "renderer/tr_light.c", "renderer/tr_surface.c", "renderer/tr_sky.c"], targets: ["src/render/dlight.ts", "src/render/world.ts", "src/render/material-registry.ts", "src/render/picture-material.ts"], evidence: ["tests/dlight.test.ts", "tests/world.test.ts", "tests/material-remap.test.ts"] },
  { sources: ["client/cl_ui.c", "client/cl_cgame.c", "qcommon/vm.c", "qcommon/files.c"], targets: ["src/engine/client-modules.ts", "src/engine/client.ts"], evidence: ["tests/client-modules.test.ts"] },
  { sources: ["client/cl_ui.c", "client/cl_cgame.c", "client/cl_parse.c"], targets: ["src/engine/client-session.ts"], evidence: ["tests/client-session.test.ts", "tests/base-ui-connect-screen.test.ts"] },
  { sources: ["q3_ui/ui_connect.c"], targets: ["src/ui/base/connect-screen.ts"], evidence: ["tests/base-ui-connect-screen.test.ts"] },
  { sources: ["client/cl_input.c", "client/cl_net_chan.c"], targets: ["src/engine/client-input.ts", "src/engine/client-session.ts"], evidence: ["tests/client-input.test.ts", "tests/client-packet-write.test.ts", "tests/client-packet-delivery.test.ts", "tests/client-packet-rate.test.ts", "tests/engine-client-admission.test.ts"] },
  { sources: ["client/cl_main.c"], targets: ["src/engine/client-admission.ts"], evidence: ["tests/client-userinfo.test.ts"] },
  { sources: ["client/cl_main.c"], targets: ["src/engine/client-cvars.ts", "src/engine/client-console-commands.ts"], evidence: ["tests/client-console-commands.test.ts"] },
  { sources: ["client/cl_main.c", "client/cl_cgame.c", "client/cl_ui.c", "qcommon/common.c"], targets: ["src/engine/client.ts", "src/engine/client-host.ts", "src/main.ts"], evidence: ["tests/client-session.test.ts", "tests/common-frame.test.ts", "tests/engine-screen.test.ts", "docs/STATUS.md"] },
  { sources: ["client/cl_main.c", "client/cl_parse.c", "qcommon/files.c"], targets: ["src/engine/client-demo-recording.ts", "src/engine/client-session.ts", "src/assets/writable-files.ts"], evidence: ["tests/client-demo-recording.test.ts"] },
  { sources: ["client/cl_scrn.c"], targets: ["src/engine/screen.ts"], evidence: ["tests/engine-screen.test.ts"] },
  { sources: ["client/cl_cgame.c", "cgame/cg_main.c", "cgame/cg_view.c"], targets: ["src/cgame/client-level.ts"], evidence: ["tests/client-level.test.ts", "tests/client-level-failure.test.ts"] },
  { sources: ["client/snd_dma.c"], targets: ["src/engine/sound.ts"], evidence: ["tests/engine-sound.test.ts"] },
  { sources: ["client/cl_cin.c", "client/snd_dma.c"], targets: ["src/engine/cinematics.ts", "src/audio/mixer.ts"], evidence: ["tests/engine-cinematics.test.ts", "tests/sound-output.test.ts"] },
  { sources: ["client/cl_main.c", "client/cl_ui.c", "unix/unix_net.c"], targets: ["src/engine/server-browser.ts", "src/platform/network.ts"], evidence: ["tests/server-browser.test.ts", "tests/network.test.ts"] },
  { sources: ["client/snd_dma.c", "client/snd_mix.c"], targets: ["src/engine/sound-frame.ts", "src/engine/sound-output.ts", "src/audio/mixer.ts", "src/audio/music.ts"], evidence: ["tests/sound-frame.test.ts", "tests/sound-output.test.ts", "tests/audio.test.ts", "tests/music.test.ts"] },
  { sources: ["renderer/tr_init.c", "renderer/tr_image.c", "renderer/tr_model.c", "unix/linux_glimp.c"], targets: ["src/render/configuration.ts", "src/render/settings.ts", "src/platform/sdl.ts"], evidence: ["tests/renderer-configuration.test.ts", "tests/render-settings.test.ts", "tests/engine-client-video.test.ts", "tests/engine-client-stencil.test.ts"] },
  { sources: ["qcommon/common.c", "client/cl_main.c", "client/cl_ui.c"], targets: ["src/engine/cd-key.ts", "src/engine/common-console.ts"], evidence: ["tests/engine-cd-key.test.ts"] },
  { sources: ["q3_ui/ui_cdkey.c", "q3_ui/ui_mfield.c"], targets: ["src/ui/base/cd-key.ts", "src/ui/base/field.ts"], evidence: ["tests/base-ui-cd-key.test.ts"] },
  { sources: ["unix/linux_snd.c"], targets: ["src/platform/audio.ts"], evidence: ["tests/sdl-audio.test.ts", "tools/audio-smoke.ts"] },
  { sources: ["unix/linux_glimp.c"], targets: ["src/platform/sdl.ts", "src/platform/gl.ts"], evidence: ["tests/sdl.test.ts", "tests/gl-renderer.test.ts", "tools/sdl-smoke.ts", "tools/gl-smoke.ts"] },
  { sources: ["unix/linux_glimp.c", "unix/linux_joystick.c"], targets: ["src/platform/sdl-game-input.ts", "src/platform/sdl.ts"], evidence: ["tests/sdl-game-input.test.ts"] },
  { sources: ["unix/unix_main.c"], targets: ["src/platform/graphical-input.ts"], evidence: ["tests/sdl-game-input.test.ts"] },
  { sources: ["botlib/aasfile.h", "botlib/be_aas_file.c", "botlib/be_aas_sample.c"], targets: ["src/botlib/aas.ts"], evidence: ["tests/aas.test.ts"] },
  { sources: ["client/cl_cin.c"], targets: ["src/cinematic/roq.ts", "src/cinematic/roq-stream.ts", "src/engine/cinematics.ts"], evidence: ["tests/roq.test.ts", "tests/engine-cinematics.test.ts", "tests/cinematic-playback.test.ts"] },
  { sources: ["jpeg-6/jdmarker.c", "jpeg-6/jdhuff.c", "jpeg-6/jdmainct.c", "jpeg-6/jdsample.c", "jpeg-6/jdcolor.c"], targets: ["src/assets/jpeg.ts"], evidence: ["tests/jpeg.test.ts"] },
  { sources: ["qcommon/md4.c", "qcommon/files.c"], targets: ["src/core/md4.ts", "src/assets/pk3.ts"], evidence: ["tests/md4.test.ts", "tests/pk3.test.ts"] },
  { sources: ["qcommon/cm_load.c", "qcommon/cm_test.c", "qcommon/cm_trace.c"], targets: ["src/collision/topology.ts", "src/collision/model.ts"], evidence: ["tests/collision-topology.test.ts", "tests/collision-model.test.ts", "tests/collision-oracle.test.ts"] },
  { sources: ["game/g_public.h", "game/g_local.h", "game/g_utils.c", "server/sv_world.c"], targets: ["src/shared/entity-shared.ts", "src/game/state.ts", "src/game/entities.ts", "src/server/world.ts"], evidence: ["tests/game-state.test.ts", "tests/game-entities.test.ts", "tests/server-world.test.ts"] },
  { sources: ["game/g_combat.c", "game/g_team.c"], targets: ["src/game/combat.ts"], evidence: ["tests/combat.test.ts"] },
  { sources: ["game/g_items.c"], targets: ["src/game/item-pickup.ts"], evidence: ["tests/item-pickup.test.ts"] },
  { sources: ["game/g_spawn.c"], targets: ["src/game/spawn.ts"], evidence: ["tests/game-spawn.test.ts"] },
  { sources: ["game/g_active.c"], targets: ["src/game/client-effects.ts"], evidence: ["tests/client-effects.test.ts"] },
  { sources: ["game/bg_misc.c"], targets: ["src/shared/snapshot-state.ts"], evidence: ["tests/snapshot-state.test.ts"] },
  { sources: ["cgame/cg_players.c"], targets: ["src/assets/animation.ts", "src/cgame/animation.ts"], evidence: ["tests/animation.test.ts", "tests/cgame-animation.test.ts"] },
  { sources: ["client/cl_parse.c", "client/cl_main.c", "server/sv_snapshot.c", "server/sv_client.c"], targets: ["src/protocol/server-message.ts", "src/protocol/demo.ts", "src/cgame/snapshot-history.ts"], evidence: ["tests/server-message.test.ts", "tests/demo.test.ts", "tests/snapshot-history.test.ts"] },
  { sources: ["client/cl_input.c", "client/cl_main.c", "server/sv_client.c", "server/sv_main.c"], targets: ["src/protocol/client-message.ts", "src/protocol/reliable.ts"], evidence: ["tests/client-message.test.ts", "tests/reliable.test.ts", "tests/loopback-movement.test.ts", "tools/verify-loopback.ts"] },
  { sources: ["unix/unix_net.c", "qcommon/net_chan.c"], targets: ["src/platform/network.ts", "src/protocol/loopback.ts"], evidence: ["tests/network.test.ts", "tests/loopback.test.ts"] },
  { sources: ["renderer/tr_sky.c", "renderer/tr_shade_calc.c", "renderer/tr_noise.c", "renderer/tr_image.c"], targets: ["src/render/sky.ts", "src/render/deform.ts", "src/render/fog.ts"], evidence: ["tests/scene-effects.test.ts", "tests/fog.test.ts", "tests/world.test.ts"] },
  { sources: ["renderer/tr_shade_calc.c", "renderer/tr_surface.c", "renderer/tr_scene.c", "cgame/tr_types.h"], targets: ["src/render/deform.ts", "src/render/refdef.ts", "src/render/tess-state.ts", "src/render/world.ts", "src/render/picture-material.ts"], evidence: ["tests/scene-effects.test.ts", "tests/world-tess.test.ts", "tests/tess-state.test.ts", "docs/STATUS.md"] },
  { sources: ["client/cl_cin.c", "renderer/tr_shader.c"], targets: ["src/cinematic/playback.ts", "src/render/world.ts"], evidence: ["tests/cinematic-playback.test.ts", "tests/video-material.test.ts"] },
  { sources: ["client/snd_dma.c"], targets: ["src/audio/music.ts", "src/audio/music-stream.ts"], evidence: ["tests/music.test.ts", "tests/engine-sound.test.ts"] },
  { sources: ["botlib/be_aas_route.c"], targets: ["src/botlib/routing.ts", "src/botlib/routing-storage.ts"], evidence: ["tests/routing.test.ts", "tests/aas-route-cache.test.ts"] },
  { sources: ["botlib/be_aas_route.c", "botlib/be_aas_def.h", "botlib/l_crc.c"], targets: ["src/botlib/aas-route-cache.ts", "src/botlib/routing.ts", "src/botlib/aas-runtime.ts", "src/botlib/library.ts"], evidence: ["tests/routing.test.ts", "tests/aas-runtime.test.ts", "tests/bot-library.test.ts", "docs/STATUS.md"] },
  { sources: ["botlib/l_script.c"], targets: ["src/script/lexer.ts", "src/script/memory.ts", "src/script/token-memory.ts"], evidence: ["tests/script-lexer.test.ts"] },
  { sources: ["botlib/l_precomp.c"], targets: ["src/script/preprocessor.ts", "src/script/source-memory.ts", "src/script/precomp-memory.ts"], evidence: ["tests/script-preprocessor.test.ts", "tests/script-source-reader.test.ts"] },
  { sources: ["game/bg_lib.c"], targets: ["src/game/numeric.ts", "src/game/format.ts"], evidence: ["tests/game-numeric.test.ts", "tests/game-format.test.ts", "tests/game-spawn.test.ts"] },
  { sources: ["game/g_utils.c"], targets: ["src/game/utilities.ts"], evidence: ["tests/game-utilities.test.ts"] },
  { sources: ["game/g_arenas.c"], targets: ["src/game/arenas.ts", "src/game/runtime.ts", "src/game/state.ts"], evidence: ["tests/game-runtime.test.ts", "docs/STATUS.md"] },
  { sources: ["game/g_active.c"], targets: ["src/game/client-think.ts", "src/game/client-policy.ts"], evidence: ["tests/client-think.test.ts", "tests/client-policy.test.ts"] },
  { sources: ["game/g_items.c"], targets: ["src/game/item-motion.ts", "src/game/item-lifecycle.ts"], evidence: ["tests/item-motion.test.ts", "tests/item-lifecycle.test.ts"] },
  { sources: ["cgame/cg_players.c"], targets: ["src/cgame/player-pose.ts"], evidence: ["tests/player-pose.test.ts"] },
  { sources: ["renderer/tr_light.c", "renderer/tr_bsp.c"], targets: ["src/render/lighting.ts"], evidence: ["tests/lighting.test.ts"] },
  { sources: ["renderer/tr_mesh.c", "renderer/tr_model.c"], targets: ["src/render/model-geometry.ts"], evidence: ["tests/model-geometry.test.ts"] },
  { sources: ["renderer/tr_init.c", "game/q_math.c"], targets: ["src/core/renderer-math.ts"], evidence: ["tests/renderer-math.test.ts", "tests/md3.test.ts"] },
  { sources: ["client/cl_main.c", "server/sv_main.c", "qcommon/net_chan.c"], targets: ["src/protocol/connectionless.ts"], evidence: ["tests/connectionless.test.ts", "tests/peer-protocol.test.ts", "tools/verify-peer.ts"] },
  { sources: ["game/q_math.c"], targets: ["src/shared/direction-byte.ts"], evidence: ["tests/direction-byte.test.ts"] },
  { sources: ["game/g_utils.c"], targets: ["src/game/shader-remaps.ts", "src/game/misc.ts"], evidence: ["tests/game-shader-remaps.test.ts", "tests/game-misc.test.ts"] },
  { sources: ["game/g_misc.c"], targets: ["src/game/misc.ts"], evidence: ["tests/game-misc.test.ts"] },
  { sources: ["game/g_missile.c"], targets: ["src/game/missile.ts"], evidence: ["tests/game-missile.test.ts"] },
  { sources: ["game/bg_misc.c"], targets: ["src/shared/trajectory.ts"], evidence: ["tests/trajectory-qvm.test.ts"] },
  { sources: ["game/g_combat.c"], targets: ["src/game/combat.ts"], evidence: ["tests/armor-qvm.test.ts"] },
  { sources: ["game/g_client.c", "game/g_team.c"], targets: ["src/game/client-spawn.ts"], evidence: ["tests/client-spawn.test.ts"] },
  { sources: ["game/g_mover.c"], targets: ["src/game/mover.ts"], evidence: ["tests/game-mover.test.ts"] },
  { sources: ["game/g_target.c", "game/g_trigger.c"], targets: ["src/game/targets.ts"], evidence: ["tests/game-targets.test.ts"] },
  { sources: ["botlib/be_ai_char.c", "game/chars.h"], targets: ["src/botlib/character.ts"], evidence: ["tests/bot-character.test.ts"] },
  { sources: ["botlib/be_ai_weight.c"], targets: ["src/botlib/weights.ts"], evidence: ["tests/bot-weights.test.ts"] },
  { sources: ["renderer/tr_scene.c", "renderer/tr_shade_calc.c", "renderer/tr_model.c", "renderer/tr_main.c"], targets: ["src/render/world.ts", "src/render/scene-models.ts"], evidence: ["tests/model-scene.test.ts", "tests/model-fixture.test.ts", "tools/model-fixture.ts", "tools/verify-render.ts"] },
  { sources: ["game/g_mover.c"], targets: ["src/game/mover-spawn.ts"], evidence: ["tests/game-mover-spawn.test.ts"] },
  { sources: ["game/g_trigger.c"], targets: ["src/game/triggers.ts"], evidence: ["tests/game-triggers.test.ts", "tests/game-targets.test.ts"] },
  { sources: ["game/g_session.c", "game/g_client.c"], targets: ["src/game/session.ts"], evidence: ["tests/game-session.test.ts"] },
  { sources: ["game/g_combat.c"], targets: ["src/game/death.ts"], evidence: ["tests/game-death.test.ts"] },
  { sources: ["game/g_team.c"], targets: ["src/game/team.ts"], evidence: ["tests/game-team.test.ts"] },
  { sources: ["game/g_weapon.c", "game/g_combat.c"], targets: ["src/game/weapon.ts"], evidence: ["tests/game-weapon.test.ts", "tests/combat.test.ts"] },
  { sources: ["botlib/be_ea.c", "game/be_ea.h"], targets: ["src/botlib/actions.ts"], evidence: ["tests/bot-actions.test.ts"] },
  { sources: ["botlib/be_ai_weap.c", "game/be_ai_weap.h"], targets: ["src/botlib/weapons.ts"], evidence: ["tests/bot-weapons.test.ts"] },
  { sources: ["botlib/l_struct.c", "botlib/l_struct.h"], targets: ["src/script/structure.ts"], evidence: ["tests/script-structure.test.ts"] },
  { sources: ["botlib/l_memory.c", "botlib/l_memory.h", "server/sv_bot.c"], targets: ["src/botlib/memory.ts", "src/botlib/library.ts", "src/engine/source-bots.ts"], evidence: ["tests/bot-actions.test.ts", "tests/bot-chat.test.ts", "tests/server-engine.test.ts"] },
  { sources: ["botlib/be_ai_goal.c"], targets: ["src/botlib/goals.ts"], evidence: ["tests/bot-goals.test.ts"] },
  { sources: ["botlib/be_aas_sample.c", "botlib/be_aas_reach.c", "botlib/be_aas_move.c", "botlib/be_ai_move.c"], targets: ["src/botlib/spatial.ts"], evidence: ["tests/aas-spatial.test.ts", "tests/bot-goals.test.ts"] },
  { sources: ["client/cl_cin.c"], targets: ["src/cinematic/playback.ts", "src/cinematic/roq.ts", "src/render/world.ts"], evidence: ["tests/cinematic-playback.test.ts", "tests/video-material.test.ts", "tests/render-clock.test.ts", "tools/render-clock.ts", "tools/verify-render.ts"] },
  { sources: ["game/g_main.c", "server/sv_game.c"], targets: ["src/game/runtime.ts", "src/game/match.ts"], evidence: ["tests/game-runtime.test.ts", "tests/game-match.test.ts", "tests/game-verification.test.ts", "tools/verify-game.ts"] },
  { sources: ["game/g_client.c"], targets: ["src/game/client-admission.ts"], evidence: ["tests/client-admission.test.ts"] },
  { sources: ["game/g_active.c"], targets: ["src/game/client-events.ts"], evidence: ["tests/game-client-events.test.ts"] },
  { sources: ["game/g_misc.c"], targets: ["src/game/misc-spawn.ts", "src/game/personal-portal.ts"], evidence: ["tests/game-misc-spawn.test.ts", "tests/personal-portal.test.ts"] },
  { sources: ["game/g_cmds.c"], targets: ["src/game/commands.ts"], evidence: ["tests/game-commands.test.ts"] },
  { sources: ["game/g_svcmds.c"], targets: ["src/game/server-commands.ts"], evidence: ["tests/game-server-commands.test.ts"] },
  { sources: ["botlib/be_ai_gen.c", "game/be_ai_gen.h"], targets: ["src/botlib/genetic.ts"], evidence: ["tests/bot-genetic.test.ts"] },
  { sources: ["botlib/be_ai_chat.c", "game/be_ai_chat.h"], targets: ["src/botlib/chat.ts", "src/botlib/chat-data.ts"], evidence: ["tests/bot-chat.test.ts"] },
  { sources: ["botlib/be_aas_bspq3.c"], targets: ["src/botlib/bsp-entities.ts"], evidence: ["tests/aas-entity.test.ts", "tests/aas-runtime.test.ts", "tests/bot-library.test.ts"] },
  { sources: ["botlib/be_aas_main.c", "botlib/be_aas_file.c", "botlib/be_aas_route.c"], targets: ["src/botlib/aas-runtime.ts"], evidence: ["tests/aas-runtime.test.ts", "tests/bot-library.test.ts"] },
  { sources: ["botlib/be_aas_sample.c"], targets: ["src/botlib/aas-links.ts", "src/botlib/aas-runtime.ts"], evidence: ["tests/aas-entity.test.ts", "tests/aas-runtime.test.ts"] },
  { sources: ["botlib/be_aas_cluster.c"], targets: ["src/botlib/aas-cluster.ts", "src/botlib/aas-world.ts"], evidence: ["tests/aas-cluster.test.ts", "tests/aas-runtime.test.ts"] },
  { sources: ["botlib/be_aas_reach.c"], targets: ["src/botlib/aas-reachability.ts", "src/botlib/aas-reachability-geometry.ts", "src/botlib/aas-reachability-special.ts", "src/botlib/aas-world.ts"], evidence: ["tests/aas-reachability.test.ts", "tests/aas-reachability-special.test.ts", "tests/aas-runtime.test.ts"] },
  { sources: ["botlib/be_aas_optimize.c"], targets: ["src/botlib/aas-optimize.ts", "src/botlib/aas-world.ts"], evidence: ["tests/aas-optimize.test.ts", "tests/aas-runtime.test.ts"] },
  { sources: ["botlib/be_aas_file.c", "botlib/aasfile.h"], targets: ["src/botlib/aas-file.ts"], evidence: ["tests/aas-file.test.ts", "tests/aas-runtime.test.ts"] },
  { sources: ["botlib/be_aas_def.h"], targets: ["src/botlib/aas-world.ts"], evidence: ["tests/aas-cluster.test.ts", "tests/aas-reachability.test.ts", "tests/aas-optimize.test.ts", "tests/aas-runtime.test.ts"] },
  { sources: ["botlib/be_aas_main.c"], targets: ["src/botlib/aas-runtime.ts"], evidence: ["tests/aas-cluster.test.ts", "tests/aas-reachability.test.ts", "tests/aas-optimize.test.ts", "tests/aas-file.test.ts", "tests/aas-runtime.test.ts"] },
  { sources: ["botlib/be_aas_debug.c"], targets: ["src/botlib/aas-debug.ts", "src/server/bot-debug.ts"], evidence: ["tests/bot-debug.test.ts", "tests/aas-reachability-special.test.ts"] },
  { sources: ["server/sv_bot.c"], targets: ["src/server/bot-debug.ts"], evidence: ["tests/bot-debug.test.ts"] },
  { sources: ["renderer/tr_main.c", "renderer/tr_backend.c", "renderer/tr_cmds.c", "renderer/tr_init.c"], targets: ["src/render/world.ts", "src/render/types.ts", "src/render/commands.ts", "src/render/settings.ts", "src/render/tess-state.ts", "src/render/portal.ts", "src/render/cpu/rasterizer.ts", "src/render/gl/renderer.ts"], evidence: ["tests/render-view.test.ts", "tests/render-commands.test.ts", "tests/render-settings.test.ts", "tests/cpu-debug-draw.test.ts", "tests/gl-debug-draw.test.ts", "tests/portal.test.ts", "docs/STATUS.md"] },
  { sources: ["server/sv_bot.c", "botlib/be_interface.c"], targets: ["src/server/bot-debug.ts", "src/engine/source-bots.ts", "src/botlib/library.ts", "src/engine/server-engine.ts"], evidence: ["tests/bot-debug.test.ts", "docs/STATUS.md"] },
  { sources: ["botlib/be_interface.c"], targets: ["src/botlib/library.ts"], evidence: ["tests/bot-library.test.ts", "tests/server-engine.test.ts", "docs/STATUS.md"] },
  { sources: ["game/ai_main.h", "game/ai_dmnet.h", "game/inv.h", "game/chars.h", "game/match.h", "game/syn.h"], targets: ["src/game/ai-definitions.ts"], evidence: ["tests/game/ai-state.test.ts", "docs/STATUS.md"] },
  { sources: ["game/ai_main.h", "game/g_local.h", "game/ai_main.c"], targets: ["src/game/ai-state.ts", "src/game/ai-context.ts"], evidence: ["tests/game/ai-state.test.ts", "tests/server-engine.test.ts", "docs/STATUS.md"] },
  { sources: ["game/ai_main.c"], targets: ["src/game/ai-main.ts", "src/game/ai-input.ts", "src/game/ai-chat.ts"], evidence: ["tests/server-engine.test.ts", "docs/STATUS.md"] },
  { sources: ["game/ai_dmq3.c", "game/ai_dmq3.h"], targets: ["src/game/ai-combat.ts", "src/game/ai-navigation.ts", "src/game/ai-orders.ts", "src/game/ai-context.ts"], evidence: ["docs/STATUS.md"] },
  { sources: ["game/ai_dmnet.c"], targets: ["src/game/ai-decision.ts"], evidence: ["docs/STATUS.md"] },
  { sources: ["game/ai_team.c"], targets: ["src/game/ai-team.ts"], evidence: ["docs/STATUS.md"] },
  { sources: ["game/ai_chat.c"], targets: ["src/game/ai-chat.ts"], evidence: ["docs/STATUS.md"] },
  { sources: ["game/ai_cmd.c"], targets: ["src/game/ai-command.ts"], evidence: ["tests/game/ai-team-goal-diagnostic.test.ts", "docs/STATUS.md"] },
  { sources: ["q3_ui/ui_spreset.c"], targets: ["src/ui/base/sp-reset.ts", "src/ui/base/ui.ts"], evidence: ["tests/base-ui-sp-reset.test.ts", "docs/STATUS.md"] },
  { sources: ["game/ai_vcmd.c"], targets: ["src/game/ai-voice.ts"], evidence: ["docs/STATUS.md"] },
  { sources: ["game/g_bot.c"], targets: ["src/game/bots.ts"], evidence: ["tests/game-bots.test.ts", "docs/STATUS.md"] },
  { sources: ["server/sv_bot.c", "server/sv_game.c"], targets: ["src/server/bot-adapter.ts"], evidence: ["tests/server-engine.test.ts", "docs/STATUS.md"] },
  { sources: ["server/sv_bot.c", "game/g_main.c", "game/g_bot.c", "game/ai_main.c"], targets: ["src/engine/source-bots.ts", "src/game/runtime.ts"], evidence: ["tests/server-engine.test.ts", "tests/game-runtime.test.ts", "docs/STATUS.md"] },
  { sources: ["server/sv_bot.c", "server/sv_init.c", "server/sv_game.c"], targets: ["src/engine/server-engine.ts"], evidence: ["tests/server-engine.test.ts", "docs/STATUS.md"] },
  { sources: ["server/sv_main.c"], targets: ["src/server/frame.ts", "src/engine/server-engine.ts"], evidence: ["tests/server-frame.test.ts", "tests/server-engine.test.ts", "docs/STATUS.md"] },
  { sources: ["cgame/cg_snapshot.c", "cgame/cg_local.h"], targets: ["src/cgame/state.ts", "src/cgame/snapshots.ts"], evidence: ["tests/cgame-snapshots.test.ts"] },
  { sources: ["cgame/cg_predict.c", "game/bg_misc.c"], targets: ["src/cgame/prediction.ts", "src/shared/jump-pad.ts"], evidence: ["tests/cgame-prediction.test.ts", "tests/game-triggers.test.ts"] },
  { sources: ["cgame/cg_ents.c"], targets: ["src/cgame/entities.ts"], evidence: ["tests/cgame-entities.test.ts"] },
  { sources: ["ui/ui_shared.c", "ui/ui_shared.h", "ui/ui_main.c", "cgame/cg_main.c"], targets: ["src/ui/menu.ts"], evidence: ["tests/menu.test.ts"] },
  { sources: ["renderer/tr_font.c", "renderer/tr_backend.c", "cgame/cg_drawtools.c", "q3_ui/ui_atoms.c", "ui/ui_shared.c", "cgame/cg_draw.c"], targets: ["src/render/draw2d.ts", "src/render/font.ts", "src/render/font-registry.ts"], evidence: ["tests/draw2d.test.ts", "tests/font.test.ts"] },
  { sources: ["game/q_math.c", "game/bg_pmove.c"], targets: ["src/core/qvm-math.ts", "src/shared/movement.ts"], evidence: ["tests/qvm-math.test.ts", "tests/movement.test.ts"] },
  { sources: ["game/g_main.c", "game/g_team.c", "game/g_cmds.c"], targets: ["src/game/runtime.ts", "src/game/team.ts", "src/game/match.ts"], evidence: ["tools/game-verification-harness.ts", "tools/verify-game-modes.ts", "tests/game-mode-verification.test.ts", ".artifacts/game-modes-root.json"] },
  { sources: ["cgame/cg_playerstate.c"], targets: ["src/cgame/player-state.ts"], evidence: ["tests/cgame-player-state.test.ts"] },
  { sources: ["cgame/cg_players.c", "cgame/cg_local.h"], targets: ["src/cgame/players.ts", "src/cgame/client-info.ts", "src/cgame/player-pose.ts", "src/cgame/animation.ts"], evidence: ["tests/cgame-players.test.ts", "tests/player-pose.test.ts", "tests/cgame-animation.test.ts"] },
  { sources: ["cgame/cg_event.c"], targets: ["src/cgame/events.ts"], evidence: ["tests/cgame-events.test.ts"] },
  { sources: ["cgame/cg_weapons.c"], targets: ["src/cgame/weapons.ts"], evidence: ["tests/cgame-weapons.test.ts"] },
  { sources: ["cgame/cg_effects.c"], targets: ["src/cgame/effects.ts"], evidence: ["tests/cgame-effects.test.ts"] },
  { sources: ["cgame/cg_localents.c"], targets: ["src/cgame/local-entities.ts"], evidence: ["tests/cgame-local-entities.test.ts"] },
  { sources: ["cgame/cg_marks.c"], targets: ["src/cgame/marks.ts", "src/cgame/particles.ts"], evidence: ["tests/cgame-marks.test.ts", "tests/cgame-marks-native.test.ts", "tests/cgame-particles.test.ts", "tests/marks-retail.test.ts"] },
  { sources: ["renderer/tr_marks.c"], targets: ["src/render/marks.ts"], evidence: ["tests/render-marks.test.ts", "tests/render-marks-native.test.ts", "tests/marks-retail.test.ts"] },
  { sources: ["cgame/cg_view.c", "cgame/tr_types.h"], targets: ["src/cgame/view.ts", "src/render/refdef.ts"], evidence: ["tests/cgame-view.test.ts"] },
  { sources: ["cgame/cg_servercmds.c", "cgame/cg_main.c", "game/q_shared.c"], targets: ["src/cgame/server-commands.ts", "src/core/info-string.ts"], evidence: ["tests/cgame-server-commands.test.ts"] },
  { sources: ["renderer/tr_scene.c", "renderer/tr_surface.c", "renderer/tr_shade_calc.c", "cgame/tr_types.h"], targets: ["src/render/ref-entity.ts", "src/render/world.ts", "src/render/deform.ts"], evidence: ["tests/entity-primitives.test.ts", "tests/entity-primitives-retail.test.ts", "tests/model-scene.test.ts", "tests/scene-effects.test.ts"] },
  { sources: ["ui/ui_shared.c", "ui/ui_shared.h"], targets: ["src/ui/runtime.ts"], evidence: ["tests/ui-runtime.test.ts"] },
  { sources: ["cgame/cg_main.c"], targets: ["src/cgame/config.ts", "src/cgame/media.ts"], evidence: ["tests/cgame-config.test.ts", "tests/cgame-media.test.ts"] },
  { sources: ["client/snd_dma.c", "client/snd_mem.c"], targets: ["src/cgame/sound-bank.ts"], evidence: ["tests/cgame-sound-bank.test.ts"] },
  { sources: ["cgame/cg_consolecmds.c"], targets: ["src/cgame/console.ts"], evidence: ["tests/cgame-console.test.ts"] },
  { sources: ["cgame/cg_view.c"], targets: ["src/cgame/frame-audio.ts"], evidence: ["tests/cgame-frame-audio.test.ts"] },
  { sources: ["cgame/cg_drawtools.c", "cgame/cg_info.c"], targets: ["src/cgame/draw-tools.ts", "src/cgame/info.ts"], evidence: ["tests/cgame-draw-tools.test.ts", "tests/cgame-info.test.ts"] },
  { sources: ["renderer/tr_main.c", "renderer/tr_backend.c", "renderer/tr_scene.c"], targets: ["src/render/view.ts", "src/render/world.ts", "src/render/refdef.ts"], evidence: ["tests/render-view.test.ts"] },
  { sources: ["renderer/tr_shader.c", "renderer/tr_shade.c", "renderer/tr_surface.c"], targets: ["src/render/material-registry.ts", "src/render/material-flags.ts", "src/render/world.ts"], evidence: ["tests/material-remap.test.ts"] },
  { sources: ["server/server.h", "server/sv_init.c", "server/sv_main.c"], targets: ["src/server/state.ts", "src/server/configstrings.ts"], evidence: ["tests/server-state.test.ts", "tests/server-configstrings.test.ts"] },
  { sources: ["server/sv_snapshot.c", "server/sv_init.c"], targets: ["src/server/snapshots.ts"], evidence: ["tests/server-snapshots.test.ts"] },
  { sources: ["cgame/cg_view.c"], targets: ["src/cgame/frame-audio.ts"], evidence: ["tests/frame-audio-fixture.ts", "tests/cgame-frame-audio-native.test.ts"] },
];

const notApplicableEvidence = new Map<string, string>([
  ["code/game/g_rankings.c", "docs/GROUNDING.md"],
  ["code/game/g_rankings.h", "docs/GROUNDING.md"],
  ["code/server/sv_rankings.c", "docs/GROUNDING.md"],
  ["code/q3_ui/ui_login.c", "docs/GROUNDING.md"],
  ["code/q3_ui/ui_rankings.c", "docs/GROUNDING.md"],
  ["code/q3_ui/ui_rankstatus.c", "docs/GROUNDING.md"],
  ["code/q3_ui/ui_signup.c", "docs/GROUNDING.md"],
  ["code/q3_ui/ui_specifyleague.c", "docs/GROUNDING.md"],
  ["code/ui/ui_util.c", "docs/SOURCE_EXAMINATION.md"],
]);

const path = "docs/source-inventory.json";
const previous: unknown = await Bun.file(path).json();
const inventory = await inventorySource(process.argv[2] ?? "/home/buzzkill/Projects/qsrc/quake-iii-arena", previous);
const sourcePaths = new Set(inventory.files.map(file => file.path));
for (const [source, evidence] of notApplicableEvidence) {
  if (!sourcePaths.has(source)) throw new Error(`Coverage source does not exist in inventory: ${source}`);
  if (!await Bun.file(evidence).exists()) throw new Error(`Coverage evidence does not exist: ${evidence}`);
}
const bySource = new Map<string, Mapping>();
for (const mapping of mappings) {
  for (const target of [...mapping.targets, ...mapping.evidence]) {
    if (!await Bun.file(target).exists()) throw new Error(`Coverage evidence does not exist: ${target}`);
  }
  for (const source of mapping.sources) {
    const key = sourcePaths.has(`code/${source}`) ? `code/${source}` : source;
    if (!sourcePaths.has(key)) throw new Error(`Coverage source does not exist in inventory: ${key}`);
    const existing = bySource.get(key);
    bySource.set(key, {
      sources: [source],
      targets: [...new Set([...(existing?.targets ?? []), ...mapping.targets])],
      evidence: [...new Set([...(existing?.evidence ?? []), ...mapping.evidence])],
    });
  }
}
const files: SourceInventoryFile[] = inventory.files.map(file => {
  const exclusionEvidence = notApplicableEvidence.get(file.path);
  if (exclusionEvidence !== undefined) return {
    ...file,
    evidence: [...new Set([...file.evidence, exclusionEvidence])],
    status: "not-applicable",
  };
  const mapping = bySource.get(file.path);
  if (mapping === undefined) return file;
  return {
    ...file,
    targetFiles: [...new Set([...file.targetFiles, ...mapping.targets])],
    evidence: [...new Set([...file.evidence, ...mapping.evidence])],
    status: file.status === "planned" ? "in-progress" : file.status,
  };
});
await Bun.write(path, JSON.stringify({ ...inventory, files }, null, 2) + "\n");
process.stdout.write(`Recorded source mappings for ${files.filter(file => file.targetFiles.length > 0).length} files; full-file completion remains unclaimed.\n`);
